import type { CreatePageData } from "./_shared";
const data: CreatePageData = {
  title: "Create AI Get Ready With Me Videos — GRWM Content",
  readTime: "7 min",
  meta: "Create AI GRWM videos that showcase products in a getting-ready routine. Includes script framework, hook templates, and best practices for Get Ready With Me content.",
  intro: "GRWM (Get Ready With Me) videos have over 100 billion views on TikTok. The format is simple — someone gets ready while talking to the camera — but the engagement is extraordinary. GRWM videos combine product showcase with personal storytelling in a way that feels intimate and authentic. Viewers watch because it feels like getting ready with a friend. For beauty, fashion, and lifestyle brands, GRWM is the ultimate product placement format. Every product used in the routine gets organic screen time, and the casual narration serves as a mini-review for each one. AI-generated GRWM videos let you produce this high-engagement format on demand — featuring your products in realistic getting-ready routines without coordinating with creators.",
  what: {
    definition: "A GRWM video shows someone getting ready — doing their makeup, choosing an outfit, styling their hair — while chatting casually with the camera. Products are showcased through use, not promotion, making it one of the most natural product placement formats.",
    reasons: [
      { label: "Intimate format", text: "GRWM videos feel like a private conversation. The getting-ready setting is inherently personal, which creates a sense of closeness between the creator and viewer. This intimacy translates to higher trust and stronger product recommendations." },
      { label: "Multi-product showcase", text: "A single GRWM video can feature 5–10 products naturally. Each product gets screen time as it's applied or used, serving as a mini-demo within the routine. This makes GRWM the most efficient format for showcasing product lines." },
      { label: "Storytelling vehicle", text: "The getting-ready format provides a natural backdrop for conversation. Creators share stories, opinions, and recommendations while applying products — the content feels like entertainment, not advertising." },
    ],
  },
  framework: [
    { step: "The Hook", time: "0–3 seconds", what: "Set the occasion and create curiosity about the routine or the story you're about to tell.", examples: ["\"GRWM for a first date. I'm going all out tonight.\"", "\"Get ready with me while I tell you about the product that replaced my entire makeup bag.\""], why: "The occasion ('first date') creates context and stakes. The product tease ('replaced my entire makeup bag') creates curiosity. Both give the viewer a reason to watch the full routine.", mistake: "Starting with 'Hey guys, GRWM!' without context. The occasion or story hook is what differentiates your GRWM from thousands of others." },
    { step: "The Setup", time: "3–8 seconds", what: "Begin the routine with skincare or base products. Chat naturally about the occasion or topic.", examples: ["\"Starting with skincare because I need this to look flawless tonight. Using my [product] — this is the one that gives me that glass skin base. Two pumps, press it in, and we're good.\""], why: "Starting with skincare establishes the routine flow. The product mention is natural because it's part of the process. 'Glass skin base' describes the benefit in aspirational language.", mistake: "Rushing through the routine. GRWM viewers want to see each step — the process IS the content." },
    { step: "The Payoff", time: "8–20 seconds", what: "Continue through the routine, featuring your hero product with slightly more detail. Share the story or topic you teased in the hook.", examples: ["\"Okay now the star of the show — this foundation. I've tried literally 30 foundations and this is the only one that doesn't oxidize on my skin. Watch this coverage... see? One layer and my skin looks airbrushed. I'm obsessed.\""], why: "Calling it 'the star of the show' signals importance without breaking the routine flow. The '30 foundations' detail establishes authority. The visual proof ('watch this coverage') lets the product speak for itself.", mistake: "Turning the GRWM into a product review. Keep the routine flowing — the product is part of the process, not the entire focus." },
    { step: "The CTA", time: "last 3–5 seconds", what: "Show the finished look and direct viewers to the products.", examples: ["\"And that's the look. Everything I used is linked in bio — but if you only get one thing, get the foundation.\"", "\"Ready. Wish me luck tonight. Products linked below.\""], why: "Showing the finished look provides the payoff viewers waited for. Recommending one standout product simplifies the purchase decision." },
  ],
  exampleScript: `[HOOK — 0-3s]\n"GRWM for a wedding this weekend. I need to look good for 12 hours straight."\n[Mirror setup, starting skincare]\n\n[SETUP — 3-8s]\n"Starting with [product] moisturizer because I need a hydrated base that won't get cakey by hour 6. This stuff is incredible — it's like a primer and moisturizer in one. My makeup literally melts into my skin after this."\n[Apply moisturizer, show texture]\n\n[PAYOFF — 8-18s]\n"Now foundation — and this is the game-changer. [Product] in shade [shade]. One pump covers everything. No oxidizing, no transfer, and it lasts ALL day. I wore this to a 10-hour event last month and it still looked fresh at midnight. I'm never going back to anything else."\n[Apply foundation, show coverage, show finish]\n\n[CTA — 18-22s]\n"Final look. I feel amazing. Everything is linked in bio — the foundation is the must-have. Trust me."\n[Show finished look, confident smile, point to link]`,
  hooks: [
    { line: "GRWM using only products under $30. The results might surprise you.", trigger: "Budget constraint creates a challenge format within the GRWM. Viewers want to see if affordable products can deliver premium results.", products: "Affordable beauty, drugstore skincare, budget fashion" },
    { line: "Get ready with me while I tell you about the worst date I've ever been on.", trigger: "Story hook combined with GRWM format. The viewer stays for the story and absorbs the product recommendations along the way.", products: "Any beauty or fashion product — the story is the retention driver" },
    { line: "The 5-minute GRWM that looks like I spent an hour. Here's every product.", trigger: "Speed and efficiency appeal. Viewers want to achieve maximum results with minimum effort.", products: "Multi-use products, time-saving beauty tools, minimal makeup routines" },
  ],
  bestPractices: [
    { label: "Ideal length", text: "30–60 seconds for social, 5–15 minutes for YouTube. Social GRWM should focus on 3–4 key products; YouTube can show the full routine." },
    { label: "Occasion context", text: "Always set an occasion — date night, work event, wedding, casual brunch. The occasion gives the routine purpose and helps viewers find content relevant to their own upcoming events." },
    { label: "Product pacing", text: "Give your hero product 2–3x more screen time than other products. Mention it by name, show the application, and comment on the result. Other products get brief mentions." },
    { label: "Conversational tone", text: "GRWM should feel like chatting with a friend. Include tangents, opinions, and personal stories. The casual conversation is what makes the format engaging." },
    { label: "Mirror or front-facing", text: "Film in mirror view or front-facing camera. The viewer should feel like they're sitting across from you while you get ready. This perspective creates the intimate GRWM feel." },
    { label: "Captions", text: "Label each product as it appears — product name, shade, and price. Use a consistent caption style throughout so viewers can screenshot their favorites." },
  ],
  whenToUse: {
    stage: "Top to mid funnel. GRWM content attracts beauty and lifestyle audiences through entertainment value. Product discovery happens naturally within the routine.",
    audience: "Beauty enthusiasts, fashion-conscious consumers, and lifestyle content viewers. Primarily women 18–35, but the format works for any demographic that has a 'getting ready' routine.",
    platforms: "TikTok (highest GRWM engagement), Instagram Reels, YouTube (long-form GRWM). Also works on Pinterest as routine inspiration content.",
    pairWith: "Follow GRWM videos with dedicated product reviews for the hero product. The GRWM introduces it in context; the review provides the depth needed to convert.",
  },
  ctaLine: "Create GRWM videos that showcase your products naturally. No influencers, no scheduling, no creative briefs.",
};
export default data;