import type { PlatformPageData } from "./_shared";

const data: PlatformPageData = {
  platform: "Connected TV (CTV)",
  h1: "AI Video Ads for Connected TV (CTV) & OTT (2026)",
  verified: "March 2026",
  meta: "Create AI video ads for Connected TV and OTT platforms — exact specs, 3 scripts for streaming ad placements, and the CTV strategy that works in 2026.",
  intro: "Connected TV ad spend is projected to hit $40B+ in 2026. CTV ads reach cord-cutters watching content on Roku, Fire TV, Apple TV, Samsung TV+, and streaming services with ad-supported tiers. The format is non-skippable, full-screen, and sound-on — the most premium ad environment available. UGC-style CTV ads are emerging as a high-performing format because they contrast with the polished brand spots that dominate streaming. A casual, authentic testimonial between episodes of a show feels refreshingly real. This guide covers how to create CTV-ready video ads.",
  specs: [
    { label: "Aspect ratio", value: "16:9 (landscape, required — TV screens are horizontal)" },
    { label: "Resolution", value: "1920×1080 (1080p) minimum. 3840×2160 (4K) preferred" },
    { label: "Video duration", value: "15 seconds or 30 seconds (standard). Some platforms accept 6s, 60s" },
    { label: "Max file size", value: "Varies by platform. Generally 1–4 GB" },
    { label: "File formats", value: ".mp4, .mov (H.264 or H.265 encoding)" },
    { label: "Sound", value: "Required — CTV always plays with sound at TV volume" },
    { label: "Captions", value: "Recommended for accessibility" },
    { label: "Bitrate", value: "15,000–25,000 kbps for 1080p. Higher for 4K" },
    { label: "Frame rate", value: "23.976, 24, 25, or 29.97 fps" },
    { label: "Audio", value: "AAC stereo, 128 kbps minimum. -24 LUFS loudness standard" },
  ],
  formats: [
    {
      name: "The Living Room Testimonial",
      why: "CTV viewers are watching on their couch. A testimonial that feels like a friend sitting next to them sharing a recommendation matches the intimate, relaxed viewing context. It contrasts with the polished brand spots and stands out.",
      structure: [
        { time: "0–3s", desc: "Hook — warm, conversational opening. \"Can I tell you about something?\"" },
        { time: "3–12s", desc: "Story — the problem, the discovery, the experience. Relaxed pacing" },
        { time: "12–22s", desc: "Result — specific outcome, genuine enthusiasm" },
        { time: "22–28s", desc: "CTA — \"Search [brand name]\" or \"Visit [URL]\" — no clicking on TV" },
      ],
      length: "25–30 seconds",
      firstFrame: "Person in a comfortable home setting. Warm lighting, relaxed posture.",
    },
    {
      name: "The 15-Second Spot",
      why: "15-second non-skippable ads are the most common CTV format. Every second must earn its place. This format delivers one clear message with one proof point and one CTA.",
      structure: [
        { time: "0–3s", desc: "Hook — one bold statement or question" },
        { time: "3–9s", desc: "Proof — one specific result, metric, or demonstration" },
        { time: "9–13s", desc: "Product — show the product clearly with key benefit" },
        { time: "13–15s", desc: "CTA — brand name + URL or search prompt" },
      ],
      length: "15 seconds exactly",
      firstFrame: "Attention-grabbing opening — face, bold text, or product in motion.",
    },
    {
      name: "The Brand Story",
      why: "CTV's 30-second format gives you room for a mini-narrative. A founder or customer telling a genuine story about why the product exists or how it changed their life creates emotional connection that drives brand recall.",
      structure: [
        { time: "0–5s", desc: "Setup — introduce the person and the problem they faced" },
        { time: "5–15s", desc: "Journey — what they tried, what failed, what they discovered" },
        { time: "15–25s", desc: "Resolution — how the product solved it, with specific results" },
        { time: "25–30s", desc: "Brand + CTA — logo, URL, search prompt" },
      ],
      length: "30 seconds exactly",
      firstFrame: "Person in a real environment. Authentic, not staged.",
    },
  ],
  scripts: [
    {
      name: "The 30-Second Testimonial",
      bestFor: "Any consumer product, brand awareness + consideration",
      duration: "30 seconds exactly",
      script: `[HOOK — 0-3s]\n"I want to tell you about something that actually\nchanged my routine."\n[Relaxed, at home, direct to camera]\n\n[STORY — 3-14s]\n"I was spending [amount] a month on [category] and\nnothing was working the way I wanted. A friend told\nme about [product] and I figured — what's one more\nthing to try, right?"\n\n[RESULT — 14-24s]\n"That was [timeframe] ago. [Specific result]. I'm not\nexaggerating — [proof point]. I've told everyone I\nknow about this. My [family member] uses it now too."\n\n[CTA — 24-30s]\n"Search [brand name] or visit [URL].\nYou'll see what I mean."\n[Product shot + logo + URL on screen]`,
      why: "The relaxed, conversational tone matches the CTV viewing context. The friend recommendation and family member detail add layers of social proof. The CTA uses \"search\" because CTV viewers can't click.",
      customization: "CTV CTAs must account for the fact that viewers can't click. Use \"search [brand name]\" or \"visit [URL]\" — give them something they can remember and act on later.",
    },
    {
      name: "The 15-Second Impact",
      bestFor: "Products with one clear benefit, frequency campaigns",
      duration: "15 seconds exactly",
      script: `[HOOK — 0-3s]\n"[Specific result] in [timeframe]. No catch."\n[Direct to camera, confident]\n\n[PROOF — 3-10s]\n"I switched to [product] [timeframe] ago.\n[Before metric] → [after metric]. That's real —\nnot marketing."\n[Show product]\n\n[CTA — 10-15s]\n"Search [brand name]. See for yourself."\n[Product shot + logo + URL]`,
      why: "15 seconds, one message, one proof point. CTV viewers remember one thing from a 15-second ad — make it the result, not the feature.",
      customization: "Pick your single most impressive metric. Don't try to communicate multiple benefits in 15 seconds — it dilutes everything.",
    },
    {
      name: "The Origin Story",
      bestFor: "DTC brands, founder-led companies, brand building",
      duration: "30 seconds exactly",
      script: `[SETUP — 0-5s]\n"I started [brand] because I was frustrated with\n[industry problem]."\n[Founder or team member, authentic setting]\n\n[PROBLEM — 5-12s]\n"Every [product category] on the market was either\n[limitation 1] or [limitation 2]. Nobody was making\nsomething that [what customers actually need]."\n\n[SOLUTION — 12-22s]\n"So we built it. [Product] does [key differentiator].\n[Specific result] for [number] customers and counting.\nWe're not the biggest — but our [metric] speaks for\nitself."\n\n[CTA — 22-30s]\n"Search [brand name] to try it.\nWe think you'll get it."\n[Product + logo + URL]`,
      why: "Origin stories build emotional connection. CTV's 30-second format is perfect for a mini-narrative. \"We're not the biggest\" is disarming and builds underdog sympathy.",
      customization: "The origin must be genuine. CTV audiences are watching premium content — they're attentive and will notice inauthenticity.",
    },
  ],
  tips: [
    { title: "CTA must be memorable, not clickable", text: "CTV viewers can't click. Your CTA must be something they can remember and act on later: a short URL, a brand name to search, or a QR code. \"Search [brand name]\" is the most effective CTV CTA." },
    { title: "Audio quality is critical", text: "CTV plays at TV volume through speakers or soundbars. Poor audio quality is immediately noticeable. Ensure clear voiceover, no background noise, and proper loudness levels (-24 LUFS)." },
    { title: "Design for the big screen", text: "CTV ads play on 40–75 inch screens. Small text, fine details, and low-resolution footage look terrible. Use large text, clear visuals, and 1080p minimum resolution." },
    { title: "Use frequency capping", text: "CTV viewers watch multiple hours per session. Without frequency capping, they'll see your ad 5+ times in one evening. Cap at 2–3 exposures per day per household." },
    { title: "Measure with incrementality, not last-click", text: "CTV doesn't have click-through attribution. Measure impact through brand lift studies, search volume increases, and incrementality testing. Don't expect direct-response metrics." },
  ],
  dos: [
    "Use 16:9 landscape — TV screens are horizontal",
    "Ensure high audio quality — CTV always plays with sound",
    "Use large, readable text — it's displayed on big screens",
    "Include a memorable CTA (search term or short URL)",
    "Use frequency capping to prevent overexposure",
    "Deliver 1080p minimum, 4K preferred",
  ],
  donts: [
    "Don't use vertical video — it looks terrible on TV screens",
    "Don't use \"click here\" or \"link in bio\" CTAs — CTV viewers can't click",
    "Don't use low-resolution footage — it's magnified on large screens",
    "Don't ignore audio quality — poor sound is immediately noticeable on TV",
    "Don't expect click-through attribution — CTV measurement is different",
    "Don't run the same ad more than 3x per day per household",
  ],
  ctaLine: "Create TV-quality video ads without a production studio. AI-powered, CTV-ready.",
};
export default data;
