import type { PlatformPageData } from "./_shared";

const data: PlatformPageData = {
  platform: "Facebook",
  h1: "AI UGC Video Ads for Facebook: The Complete Guide (2026)",
  verified: "March 2026",
  meta: "Everything you need to create AI UGC video ads for Facebook — exact specs, 3 proven scripts, creative testing strategy, and what's actually converting right now.",
  intro: "Facebook still drives more e-commerce revenue than any other paid social platform. But the game has changed. Advantage+ Shopping campaigns now dominate, and the algorithm heavily favors UGC-style creative over polished brand content. Brands running UGC-style video ads on Facebook see 1.5–2x lower CPAs compared to studio-produced content. The algorithm rewards authenticity because users engage with it more — and engagement signals tell Facebook to show the ad to more people. This guide covers exact specs, the 3 formats that convert, ready-to-use scripts, and the testing framework that works in 2026.",
  specs: [
    { label: "Aspect ratio", value: "1:1 (Feed), 9:16 (Reels/Stories), 16:9 (In-Stream)" },
    { label: "Resolution", value: "Min 1080×1080 (1:1). Recommended: 1080×1920 (9:16)" },
    { label: "Video duration", value: "Feed: 1–240 seconds. Reels: 3–90 seconds. Sweet spot: 15–30s" },
    { label: "Max file size", value: "4 GB" },
    { label: "File formats", value: ".mp4, .mov (H.264 compression recommended)" },
    { label: "Safe zone", value: "Keep text within 1080×1080 center for Feed; avoid bottom 250px for Reels" },
    { label: "Sound", value: "Optional but recommended — 65% of Facebook video is watched with sound" },
    { label: "Captions", value: "Strongly recommended — burned-in for accessibility and silent viewing" },
    { label: "Thumbnail", value: "Auto-selected or custom. First frame matters for Feed placement" },
    { label: "Text overlay", value: "Keep under 20% of frame for best delivery (soft guideline)" },
  ],
  formats: [
    {
      name: "The Feed Testimonial",
      why: "Facebook Feed is still the highest-volume placement. Testimonial-style UGC in 1:1 format blends with organic posts and gets treated like content, not ads. Advantage+ campaigns love this format because it generates high engagement signals.",
      structure: [
        { time: "0–3s", desc: "Hook — emotional or curiosity-driven opening, direct to camera" },
        { time: "3–10s", desc: "Story — the problem, what you tried, the discovery" },
        { time: "10–20s", desc: "Result — specific outcome with visual proof or detail" },
        { time: "20–25s", desc: "CTA — soft sell, \"link in bio\" or \"check it out below\"" },
      ],
      length: "20–30 seconds",
      firstFrame: "Face visible, natural setting, no branding. Should look like a friend's post in your feed.",
    },
    {
      name: "The Problem-Agitate-Solve",
      why: "Facebook's older demographic (30–55) responds strongly to problem-first framing. Name the pain, twist the knife, then present the solution. This format works especially well for retargeting audiences who already know they have the problem.",
      structure: [
        { time: "0–3s", desc: "Problem — name the specific pain point the viewer is experiencing" },
        { time: "3–8s", desc: "Agitate — describe why existing solutions fail or make it worse" },
        { time: "8–18s", desc: "Solve — introduce the product as the fix, show specific results" },
        { time: "18–22s", desc: "CTA — direct but not aggressive" },
      ],
      length: "18–25 seconds",
      firstFrame: "Frustrated or concerned expression. Text overlay with the problem statement.",
    },
    {
      name: "The Reels-First UGC",
      why: "Facebook Reels is the fastest-growing placement and gets preferential delivery. 9:16 vertical UGC that mirrors TikTok content performs well here because the format feels native to the Reels experience.",
      structure: [
        { time: "0–2s", desc: "Hook — text on screen + voiceover, movement in first frame" },
        { time: "2–8s", desc: "Quick demo or story — fast pacing, casual tone" },
        { time: "8–13s", desc: "Result or proof — show the outcome" },
        { time: "13–15s", desc: "CTA — text overlay + verbal" },
      ],
      length: "12–18 seconds",
      firstFrame: "Movement or action in the very first frame. Static openings get scrolled past.",
    },
  ],
  scripts: [
    {
      name: "The Honest Review",
      bestFor: "Cold and warm audiences, any consumer product",
      duration: "22–28 seconds",
      script: `[HOOK — 0-3s]\n"I almost didn't buy this because the ads looked too\ngood to be true. But here's what actually happened..."\n[Direct to camera, casual setting]\n\n[STORY — 3-12s]\n"I've been dealing with [problem] for years. I've tried\n[competitor 1], [competitor 2], even [extreme solution].\nNothing stuck. My friend kept pushing me to try this\nand I finally caved."\n\n[RESULT — 12-22s]\n"It's been [timeframe]. And honestly? [Specific result].\nI didn't expect it to work this fast. Look — [show proof\nor describe visible change]."\n\n[CTA — 22-26s]\n"If you've been on the fence, just try it. I wish I\nhadn't waited so long. Link below."`,
      why: "The \"too good to be true\" hook mirrors the viewer's own skepticism. Acknowledging doubt upfront builds trust. The friend recommendation adds social proof within the social proof.",
      customization: "Replace [problem], [competitors], [timeframe], and [result] with your product specifics. Keep the skeptic-to-believer arc — it's the emotional structure that converts on Facebook.",
    },
    {
      name: "The Before/After Story",
      bestFor: "Products with visible results, retargeting audiences",
      duration: "18–22 seconds",
      script: `[HOOK — 0-3s]\n"[Timeframe] ago, I looked like this..."\n[Show before state — photo, description, or re-enactment]\n\n[MIDDLE — 3-12s]\n"I started using [product] because [specific reason].\nI wasn't expecting miracles — I just wanted something\nthat actually worked."\n[Show product casually]\n\n[AFTER — 12-17s]\n"And now... [show current state]. No filter. No editing.\nThis is just [the result]."\n\n[CTA — 17-21s]\n"If your [problem area] looks like my before, try this.\nLink below."`,
      why: "Before/after is the most proven format on Facebook for products with visible results. The \"no filter\" claim adds credibility. The CTA targets people who identify with the \"before\" state.",
      customization: "The before state needs to be relatable, not extreme. If the before is too bad, viewers won't identify with it. If the after is too perfect, they won't believe it.",
    },
    {
      name: "The Quick Demo",
      bestFor: "Products with a visible use case, cold audiences on Reels",
      duration: "14–18 seconds",
      script: `[HOOK — 0-2s]\n[TEXT ON SCREEN: "Why didn't anyone tell me about this"]\n[Product in hand, start moving immediately]\n\n[DEMO — 2-10s]\n[Show product being used — quick cuts, 2 seconds per shot]\n[Voiceover: "Apply it like this. Wait 30 seconds. Done."]\n\n[RESULT — 10-14s]\n[Show the result clearly]\n[Voiceover: "Every. Single. Time. It just works."]\n\n[CTA — 14-17s]\n[TEXT ON SCREEN: "Link below 👇"]\n[Voiceover: "You're welcome."]`,
      why: "Short demos get the highest completion rates on Facebook Reels. The text hook mimics organic content. \"You're welcome\" as a CTA feels casual and confident.",
      customization: "Adapt the demo steps to your product. The key is speed — never linger on any single shot for more than 2 seconds.",
    },
  ],
  tips: [
    { title: "Run Advantage+ Shopping Campaigns with 5+ creatives", text: "Advantage+ needs creative variety to optimize. Upload at least 5 different video creatives — different hooks, different actors, different formats. The algorithm will find the winners faster than you can." },
    { title: "Test 1:1 and 9:16 separately", text: "Don't assume one aspect ratio works everywhere. 1:1 dominates Feed, 9:16 dominates Reels. Create both versions and let the algorithm allocate budget to the winner." },
    { title: "Spend $50–$100 per creative before judging", text: "Facebook's learning phase needs data. Killing a creative after $20 doesn't give the algorithm enough signal. Budget $50–$100 per variation for a fair test." },
    { title: "Refresh creatives every 14–21 days", text: "Facebook creative fatigue is slower than TikTok but still real. Monitor frequency — when it hits 2.5+, your creative is wearing out. Always have fresh creatives in the pipeline." },
    { title: "Use the same winning script with different actors", text: "When you find a script that converts, don't change the words — change the face. Generate the same script with 3–5 different AI actors to extend the creative's lifespan." },
  ],
  dos: [
    "Use 1:1 for Feed placement and 9:16 for Reels — don't force one format everywhere",
    "Add burned-in captions — Facebook autoplay is muted by default",
    "Start with a face in the first frame — faces stop the scroll on Facebook",
    "Keep the first 3 seconds emotionally charged — curiosity, surprise, or relatability",
    "Use natural lighting and casual settings — polished production signals \"ad\"",
    "Include a clear CTA in the last 3 seconds — Facebook users need direction",
  ],
  donts: [
    "Don't use the same creative for Feed and Reels without reformatting",
    "Don't start with your brand name or logo — earn attention first",
    "Don't use corporate language — Facebook audiences respond to conversational tone",
    "Don't run fewer than 3 creatives per ad set — the algorithm needs options",
    "Don't ignore Reels placement — it's where Facebook is pushing delivery in 2026",
    "Don't use stock footage — it's immediately recognizable and kills trust",
  ],
  ctaLine: "Create Facebook video ads that convert. No camera, no creators, no editing.",
};
export default data;
