import type { PlatformPageData } from "./_shared";

const data: PlatformPageData = {
  platform: "Google Demand Gen",
  h1: "AI Video Ads for Google Demand Gen Campaigns (2026)",
  verified: "March 2026",
  meta: "Create AI video ads for Google Demand Gen campaigns — specs, scripts, and strategy for YouTube, Discover, and Gmail placements in 2026.",
  intro: "Google Demand Gen campaigns run across YouTube (in-feed, Shorts, in-stream), Google Discover, and Gmail — reaching users in discovery mode across Google's entire ecosystem. The format is designed for mid-funnel engagement: catching people who aren't actively searching but are open to discovering new products. UGC-style video creative outperforms polished brand content in Demand Gen by 1.4x on click-through rate because it matches the native content feel of Discover and YouTube feeds. This guide covers how to create video ads optimized for Demand Gen's multi-surface delivery.",
  specs: [
    { label: "Aspect ratios", value: "16:9 (landscape), 1:1 (square), 9:16 (vertical) — provide all three" },
    { label: "Resolution", value: "1080p recommended for each ratio" },
    { label: "Video duration", value: "10 seconds–1 minute. Sweet spot: 15–30 seconds" },
    { label: "Max file size", value: "256 MB" },
    { label: "File formats", value: ".mp4, .mov" },
    { label: "Sound", value: "Required — most placements autoplay with sound" },
    { label: "Captions", value: "Strongly recommended — Gmail and Discover may show without sound" },
    { label: "Headlines", value: "Up to 5 headlines, 40 characters each" },
    { label: "Descriptions", value: "Up to 5 descriptions, 90 characters each" },
    { label: "CTA", value: "Selected from Google's predefined list (Shop Now, Learn More, Sign Up, etc.)" },
  ],
  formats: [
    {
      name: "The Discovery Testimonial",
      why: "Demand Gen surfaces ads in content feeds where users are browsing, not searching. A testimonial that feels like a recommendation from a friend matches this browsing context perfectly.",
      structure: [
        { time: "0–3s", desc: "Hook — personal, curiosity-driven opening" },
        { time: "3–10s", desc: "Story — brief problem and discovery narrative" },
        { time: "10–20s", desc: "Result — specific outcome that proves the product works" },
        { time: "20–25s", desc: "CTA — \"Check it out\" or \"See for yourself\"" },
      ],
      length: "20–28 seconds",
      firstFrame: "Face visible, natural setting. Should look like organic content in a feed.",
    },
    {
      name: "The Product Spotlight",
      why: "For e-commerce products, a quick product-focused video that shows the item in use works well in Discover and YouTube in-feed placements. The key is making it feel like a creator review, not a product listing.",
      structure: [
        { time: "0–2s", desc: "Hook — \"Found this and had to share...\" or product in motion" },
        { time: "2–10s", desc: "Show the product from multiple angles, in use" },
        { time: "10–15s", desc: "Key benefit — one specific thing that makes it worth buying" },
        { time: "15–18s", desc: "CTA — \"Link below\" or \"Shop now\"" },
      ],
      length: "15–20 seconds",
      firstFrame: "Product in hand or in use. Movement in the first frame.",
    },
    {
      name: "The Multi-Format Adapter",
      why: "Demand Gen serves across YouTube, Discover, and Gmail — each with different aspect ratios and contexts. This format is designed to work in all three by keeping key content in the center frame.",
      structure: [
        { time: "0–2s", desc: "Hook — centered in frame, works in 16:9, 1:1, and 9:16" },
        { time: "2–12s", desc: "Content — keep all important visuals and text in the center 60% of frame" },
        { time: "12–18s", desc: "Result or proof — centered composition" },
        { time: "18–20s", desc: "CTA — text overlay centered" },
      ],
      length: "18–22 seconds",
      firstFrame: "Centered composition that works when cropped to any aspect ratio.",
    },
  ],
  scripts: [
    {
      name: "The Feed-Native Review",
      bestFor: "Any consumer product, mid-funnel audiences",
      duration: "22–28 seconds",
      script: `[HOOK — 0-3s]\n"I keep seeing this everywhere and finally tried it.\nHere's my honest take..."\n[Direct to camera, casual, browsing-context tone]\n\n[STORY — 3-14s]\n"So [product] claims to [main benefit]. I was skeptical\nbecause I've tried [alternatives] and they all\noverpromised. But after [timeframe] of using this,\nI have to admit — [specific result]."\n\n[PROOF — 14-20s]\n"[Show result or describe metric]. That's not marketing\nspeak — that's what actually happened. And it costs\n[price point], which is [comparison]."\n\n[CTA — 20-25s]\n"If you've been thinking about trying it, just do it.\nLink below."`,
      why: "\"I keep seeing this everywhere\" mirrors the Discover/feed experience — the viewer has probably seen the product before. This hook validates their awareness and provides the review they've been looking for.",
      customization: "Adapt the skepticism level to your audience. Demand Gen reaches mid-funnel users who are aware but unconvinced. Address their specific hesitations.",
    },
    {
      name: "The Quick Product Show",
      bestFor: "E-commerce, physical products, cold-to-warm audiences",
      duration: "16–20 seconds",
      script: `[HOOK — 0-2s]\n"Okay this might be my favorite purchase this year"\n[Product in hand, start showing immediately]\n\n[SHOW — 2-12s]\n[Multiple angles, product in use]\n"The [feature 1] is [benefit]. The [feature 2] is\n[benefit]. And the best part — [key differentiator]."\n\n[CLOSE — 12-16s]\n"[Price] and it [summary of value]. I've already\nordered a second one."\n\n[CTA — 16-19s]\n"Link below. You'll see what I mean."`,
      why: "Short, product-focused, and enthusiastic without being salesy. \"My favorite purchase this year\" is a strong endorsement that feels organic in a content feed.",
      customization: "Pick 2–3 features max. Don't try to cover everything — pick the features that matter most to your target audience.",
    },
    {
      name: "The Problem Solver",
      bestFor: "Products that solve a specific pain point, retargeting",
      duration: "20–25 seconds",
      script: `[HOOK — 0-3s]\n"If you're still dealing with [common problem], you\nneed to know about this."\n[Direct to camera, empathetic tone]\n\n[PROBLEM — 3-8s]\n"I spent [time/money] trying to fix [problem] with\n[common solutions]. None of them worked because\n[reason]."\n\n[SOLUTION — 8-18s]\n"[Product] takes a different approach: [how it works].\nAfter [timeframe], [specific result]. It actually\nsolved the problem instead of just managing it."\n\n[CTA — 18-22s]\n"Check the link below. Stop wasting money on\n[solutions that don't work]."`,
      why: "Problem-first framing works well in Demand Gen because users in Discover are often browsing content related to their problems. This ad meets them where they are.",
      customization: "The problem must be specific and relatable. \"Dealing with bad skin\" is too vague. \"Spending $200/month on serums that don't work\" is specific and emotional.",
    },
  ],
  tips: [
    { title: "Provide all three aspect ratios", text: "Demand Gen serves across YouTube (16:9), Discover (1:1 and 9:16), and Gmail (1:1). Providing all three ratios gives the algorithm maximum flexibility to find the best placement." },
    { title: "Upload 5+ creative variations", text: "Demand Gen uses machine learning to optimize creative delivery. More variations = faster optimization = lower CPAs. Upload at least 5 different videos with different hooks." },
    { title: "Use lookalike audiences", text: "Demand Gen supports lookalike segments based on your customer lists. Combine UGC creative with lookalike targeting for the best mid-funnel performance." },
    { title: "Optimize for conversions, not clicks", text: "Set your campaign objective to conversions (purchases, sign-ups) rather than clicks. Demand Gen's algorithm is better at finding converters than clickers." },
    { title: "Test product feed integration", text: "For e-commerce, connect your product feed to Demand Gen. The algorithm can dynamically show relevant products alongside your video creative." },
  ],
  dos: [
    "Provide video in 16:9, 1:1, and 9:16 aspect ratios",
    "Upload at least 5 creative variations for algorithm optimization",
    "Add burned-in captions for Gmail and Discover placements",
    "Use conversions as your optimization goal, not clicks",
    "Keep key content centered for multi-format cropping",
    "Write 5 headline and 5 description variations for testing",
  ],
  donts: [
    "Don't provide only one aspect ratio — you'll miss placements",
    "Don't optimize for clicks — Demand Gen works best with conversion optimization",
    "Don't use the same creative as your Search campaigns — different intent, different creative",
    "Don't ignore Gmail placement — it's often the cheapest conversion source",
    "Don't run fewer than 3 video creatives — the algorithm needs options",
    "Don't use hard-sell CTAs — Demand Gen audiences are mid-funnel, not ready to buy immediately",
  ],
  ctaLine: "Create video ads for Google Demand Gen. Reach buyers across YouTube, Discover, and Gmail.",
};
export default data;
