import type { PlatformPageData } from "./_shared";

const data: PlatformPageData = {
  platform: "Instagram Reels",
  h1: "AI UGC Videos for Instagram Reels: What Converts in 2026",
  verified: "March 2026",
  meta: "Create AI UGC video ads for Instagram Reels — exact specs, 3 high-converting scripts, format breakdowns, and the creative strategy that's working right now.",
  intro: "Instagram Reels now accounts for over 50% of time spent on Instagram. The algorithm aggressively promotes Reels content, and UGC-style video ads in the Reels feed consistently outperform polished brand content by 1.8x on engagement and 1.4x on conversion rate. The key difference from TikTok: Instagram Reels audiences skew slightly older (25–44) and respond better to aspirational-but-authentic content. Less chaotic, more curated casual. This guide covers the exact specs, formats, scripts, and strategy for Reels ads in 2026.",
  specs: [
    { label: "Aspect ratio", value: "9:16 (required for full-screen Reels)" },
    { label: "Resolution", value: "1080×1920px recommended" },
    { label: "Video duration", value: "3–90 seconds. Sweet spot: 15–30 seconds for ads" },
    { label: "Max file size", value: "4 GB" },
    { label: "File formats", value: ".mp4, .mov" },
    { label: "Safe zone (top)", value: "Keep text below 15% from top (account name overlay)" },
    { label: "Safe zone (bottom)", value: "Avoid bottom 250px (CTA button, caption area)" },
    { label: "Safe zone (right)", value: "Avoid right 15% (like/comment/share buttons)" },
    { label: "Sound", value: "Recommended — 80% of Reels are watched with sound" },
    { label: "Captions", value: "Strongly recommended — burned-in, not auto-generated" },
  ],
  formats: [
    {
      name: "The Aspirational Testimonial",
      why: "Instagram audiences want to see the best version of themselves. Unlike TikTok's raw chaos, Reels testimonials work best when they feel authentic but slightly elevated — good lighting, clean background, confident delivery.",
      structure: [
        { time: "0–2s", desc: "Hook — confident, slightly surprising opening statement" },
        { time: "2–8s", desc: "Story — brief problem, quick discovery, emphasis on the experience" },
        { time: "8–18s", desc: "Result — show the outcome with pride, not surprise" },
        { time: "18–22s", desc: "CTA — casual but confident: \"you need this\"" },
      ],
      length: "18–25 seconds",
      firstFrame: "Well-lit face, clean background, confident expression. Aspirational but not unattainable.",
    },
    {
      name: "The Get Ready With Me (GRWM)",
      why: "GRWM is one of the most native formats on Instagram Reels. It feels like content, not advertising. The viewer watches someone go through a routine and the product is naturally woven in as one step.",
      structure: [
        { time: "0–2s", desc: "Hook — \"Get ready with me\" or \"My morning routine that changed everything\"" },
        { time: "2–12s", desc: "Routine steps — quick cuts, 2–3 seconds per step" },
        { time: "12–18s", desc: "Feature the product — pause slightly, explain why this step matters" },
        { time: "18–22s", desc: "Final look + CTA — show the result, link in bio" },
      ],
      length: "18–25 seconds",
      firstFrame: "Person in front of mirror or vanity. Natural morning/evening setting.",
    },
    {
      name: "The Trend Ride",
      why: "Instagram Reels rewards content that uses trending audio and formats. This template adapts trending Reels structures for product promotion — the viewer recognizes the format and engages before realizing it's an ad.",
      structure: [
        { time: "0–2s", desc: "Trending audio or format hook — match the current trend structure" },
        { time: "2–8s", desc: "Adapt the trend to your product story" },
        { time: "8–13s", desc: "Product reveal or result" },
        { time: "13–15s", desc: "CTA — text overlay, keep it brief" },
      ],
      length: "12–18 seconds",
      firstFrame: "Match the trending format's typical opening. Familiarity drives engagement.",
    },
  ],
  scripts: [
    {
      name: "The Glow-Up Testimonial",
      bestFor: "Beauty, skincare, fashion, wellness products",
      duration: "20–25 seconds",
      script: `[HOOK — 0-2s]\n"People keep asking me what I changed and honestly\nit's just one thing..."\n[Direct to camera, good lighting, confident]\n\n[STORY — 2-10s]\n"I used to spend so much time and money trying to\nfix [problem]. Nothing worked the way I wanted.\nThen I found [product] and decided to give it\none more shot."\n\n[RESULT — 10-18s]\n"That was [timeframe] ago. Look at [result area] now.\nI haven't used [old solution] since. This is literally\nall I use."\n[Show result naturally]\n\n[CTA — 18-23s]\n"If you're still struggling with [problem], this is it.\nLink in bio — trust me on this one."`,
      why: "The \"people keep asking\" hook implies social validation — others have already noticed the change. This is powerful on Instagram where social perception matters more than on TikTok.",
      customization: "Replace [problem], [product], [timeframe], and [result area]. Keep the confident tone — Instagram audiences respond to certainty, not hesitation.",
    },
    {
      name: "The Routine Feature",
      bestFor: "Any product that fits into a daily routine",
      duration: "18–22 seconds",
      script: `[HOOK — 0-2s]\n"My [morning/evening] routine is only 3 steps now\nand my [skin/hair/energy] has never been better"\n[Getting ready, natural setting]\n\n[ROUTINE — 2-14s]\n"Step 1: [Quick step, 2 seconds]\nStep 2: [Product — slightly longer, 4 seconds]\nThis is the one that made the biggest difference.\n[Show application/use]\nStep 3: [Final step, 2 seconds]"\n\n[RESULT — 14-18s]\n"Done. [Show final result]. Takes me 5 minutes\nand I'm out the door."\n\n[CTA — 18-21s]\n"Everything's linked in bio. But especially step 2."`,
      why: "Routine content is Instagram's bread and butter. Framing the product as \"the step that made the difference\" within a routine feels like a recommendation, not an ad.",
      customization: "The routine should be 3–5 steps max. The featured product should be step 2 or 3 — not first (too obvious) and not last (viewers may drop off).",
    },
    {
      name: "The Quick Reveal",
      bestFor: "Products with visible results, cold audiences",
      duration: "12–15 seconds",
      script: `[HOOK — 0-2s]\n[TEXT ON SCREEN: "Wait for it..."]\n[Show the before state or start of application]\n\n[BUILD — 2-8s]\n[Quick cuts of product in use]\n[Voiceover: "One step. That's it. Just watch."]\n\n[REVEAL — 8-12s]\n[Show the result — clean transition or side-by-side]\n[Voiceover: "I mean... come on."]\n\n[CTA — 12-14s]\n[TEXT ON SCREEN: "Link in bio 🔗"]\n[Voiceover: "You need this."]`,
      why: "\"Wait for it\" is one of the highest-retention hooks on Reels because it creates anticipation. The short format ensures high completion rates, which the algorithm rewards with more delivery.",
      customization: "The reveal needs to be genuinely impressive. If the before/after isn't dramatic enough, use a different format.",
    },
  ],
  tips: [
    { title: "Optimize for the Reels tab, not just Feed", text: "Reels that appear in the dedicated Reels tab get 2–3x more reach than those only shown in Feed. Use trending audio (even at low volume), 9:16 format, and native-feeling content to get Reels tab placement." },
    { title: "The first frame is your thumbnail", text: "Instagram auto-selects a thumbnail from your video. Make sure the first frame is visually compelling — a face, movement, or bold text. You can also set a custom cover image." },
    { title: "Test 3 hooks per script before changing the body", text: "The hook determines 80% of performance. Write one solid body and CTA, then generate 3–5 versions with different opening lines. Test hooks first." },
    { title: "Use carousel ads for retargeting, Reels for prospecting", text: "Reels work best for cold audiences — they feel like content. For retargeting, carousel ads with product images often outperform video. Use each format where it's strongest." },
    { title: "Post at peak engagement times", text: "For paid Reels, timing matters less (the algorithm delivers when your audience is active). For organic Reels, post between 11am–1pm and 7pm–9pm in your target timezone." },
  ],
  dos: [
    "Use 9:16 vertical format — always, no exceptions for Reels",
    "Add burned-in captions with a clean, readable font",
    "Use trending audio even at low volume — it signals native content to the algorithm",
    "Keep the visual quality slightly higher than TikTok — Instagram audiences expect it",
    "Show faces in the first frame — faces drive 38% higher engagement on Reels",
    "End with a clear CTA — Instagram users need to be told to check the link",
  ],
  donts: [
    "Don't repost TikTok videos with the TikTok watermark — Instagram deprioritizes them",
    "Don't use horizontal or square video for Reels — it wastes screen space",
    "Don't start with a logo or brand name — earn attention with the hook first",
    "Don't make Reels longer than 30 seconds for ads — completion rate drops sharply after 30s",
    "Don't use overly casual or chaotic editing — Instagram Reels audiences prefer polished-casual",
    "Don't ignore the safe zones — key content gets hidden behind UI elements",
  ],
  ctaLine: "Create Instagram Reels ads that blend in and convert. No camera needed.",
};
export default data;
