import type { PlatformPageData } from "./_shared";

const data: PlatformPageData = {
  platform: "Pinterest",
  h1: "AI UGC Video Ads for Pinterest: Idea Pins & Video Ads (2026)",
  verified: "March 2026",
  meta: "Create AI UGC video ads for Pinterest — exact specs, 3 scripts for Idea Pins and video ads, and the creative strategy that converts on Pinterest in 2026.",
  intro: "Pinterest users are planners and buyers. 85% of weekly Pinners have made a purchase based on Pins they saw from brands. Unlike TikTok or Instagram where users scroll for entertainment, Pinterest users are actively looking for ideas, products, and solutions. Video Pins and Idea Pins get 3x more engagement than static Pins, and UGC-style video content outperforms polished brand content by 1.5x on save rate — the metric that matters most on Pinterest. This guide covers how to create video ads that match Pinterest's unique intent-driven audience.",
  specs: [
    { label: "Aspect ratio", value: "2:3 (standard Pin), 9:16 (Idea Pin), 1:1 (square)" },
    { label: "Resolution", value: "1000×1500px (2:3) or 1080×1920px (9:16)" },
    { label: "Video duration", value: "4 seconds–15 minutes. Sweet spot: 15–30 seconds for ads" },
    { label: "Max file size", value: "2 GB" },
    { label: "File formats", value: ".mp4, .mov, .m4v" },
    { label: "Sound", value: "Optional — many Pinterest users browse silently" },
    { label: "Captions", value: "Required — Pinterest is a silent-browsing platform" },
    { label: "Text overlay", value: "Recommended — Pinterest users scan visually before engaging" },
    { label: "Pin title", value: "Max 100 characters. Include keywords for search" },
    { label: "Pin description", value: "Max 500 characters. Keyword-rich for Pinterest SEO" },
  ],
  formats: [
    {
      name: "The Tutorial Pin",
      why: "Pinterest users search for how-to content. A quick tutorial that shows your product in use as part of a process gets saved, shared, and drives purchase intent. Tutorial Pins have the highest save rate of any format.",
      structure: [
        { time: "0–3s", desc: "Hook — \"How to [achieve result] in [timeframe]\" with text overlay" },
        { time: "3–12s", desc: "Steps — show 3–4 quick steps with text labels for each" },
        { time: "12–18s", desc: "Result — show the final outcome clearly" },
        { time: "18–22s", desc: "CTA — \"Save this for later\" or \"Shop the link\"" },
      ],
      length: "18–25 seconds",
      firstFrame: "Bold text overlay with the tutorial title. Clean, well-lit composition.",
    },
    {
      name: "The Lifestyle Showcase",
      why: "Pinterest is aspirational. Showing your product in a beautiful, aspirational context — the perfect morning routine, the organized closet, the glowing skin — drives saves and clicks because users want to recreate that lifestyle.",
      structure: [
        { time: "0–2s", desc: "Aspirational scene — beautiful setting, product visible" },
        { time: "2–10s", desc: "Product in context — show it being used in the aspirational setting" },
        { time: "10–15s", desc: "Close-up of product + key benefit text overlay" },
        { time: "15–18s", desc: "CTA — \"Shop now\" or \"Save for later\"" },
      ],
      length: "15–20 seconds",
      firstFrame: "Aesthetically pleasing scene with warm lighting. Pinterest-worthy composition.",
    },
    {
      name: "The Before/After Reveal",
      why: "Transformation content is Pinterest gold. Before/after Pins get 2x more saves than standard product Pins because they show proof of results in a format that's easy to scan.",
      structure: [
        { time: "0–2s", desc: "Before state — text overlay: \"Before\" — show the problem" },
        { time: "2–4s", desc: "Product introduction — quick shot of the product" },
        { time: "4–10s", desc: "Application/use — show the product being used" },
        { time: "10–14s", desc: "After state — text overlay: \"After\" — show the result" },
        { time: "14–16s", desc: "CTA — \"Get the look\" or \"Shop now\"" },
      ],
      length: "14–18 seconds",
      firstFrame: "Split-screen or clear \"Before\" label. Visual contrast is key.",
    },
  ],
  scripts: [
    {
      name: "The Quick Tutorial",
      bestFor: "Beauty, home, food, DIY, fashion products",
      duration: "20–25 seconds",
      script: `[HOOK — 0-3s]\n[TEXT ON SCREEN: "How to get glass skin in 3 steps"]\n[Clean, well-lit setting]\n\n[STEP 1 — 3-8s]\n[TEXT: "Step 1: Cleanse"]\n[Show step quickly — 2-3 seconds]\n[Voiceover: "Start with a clean base"]\n\n[STEP 2 — 8-14s]\n[TEXT: "Step 2: Apply [product]"]\n[Show product application — slightly longer]\n[Voiceover: "This is the step that changes everything"]\n\n[STEP 3 — 14-18s]\n[TEXT: "Step 3: Set with SPF"]\n[Quick application]\n\n[RESULT — 18-22s]\n[TEXT: "The result ✨"]\n[Show final result — close-up]\n[Voiceover: "Glass skin. Every time."]\n\n[CTA — 22-24s]\n[TEXT: "Save this 📌 | Shop link below"]`,
      why: "Tutorial Pins are the most saved content type on Pinterest. The step-by-step format is scannable even without sound, and the \"save this\" CTA drives the engagement signal Pinterest's algorithm rewards most.",
      customization: "Replace the steps with your product's use case. Keep it to 3–4 steps max. The featured product should be step 2 — the \"game changer\" step.",
    },
    {
      name: "The Aesthetic Showcase",
      bestFor: "Lifestyle products, home decor, fashion, beauty",
      duration: "16–20 seconds",
      script: `[SCENE — 0-5s]\n[Beautiful setting — morning light, clean space]\n[Product visible in context]\n[TEXT: "My morning essential ☀️"]\n\n[USE — 5-12s]\n[Show product being used — slow, intentional movements]\n[Voiceover: "This is the one thing I never skip.\n[Key benefit] in [timeframe]."]\n\n[CLOSE-UP — 12-16s]\n[Product close-up with text overlay of key benefit]\n[Voiceover: "Worth every penny."]\n\n[CTA — 16-19s]\n[TEXT: "Shop the link 🔗 | Save for later 📌"]`,
      why: "Pinterest is a visual platform. Beautiful, aspirational content gets saved and shared. The slow, intentional pacing matches how Pinterest users browse — they're not rushing like on TikTok.",
      customization: "The setting matters as much as the product on Pinterest. Invest in the visual context — clean backgrounds, warm lighting, aesthetically pleasing composition.",
    },
    {
      name: "The Transformation Reveal",
      bestFor: "Products with visible results — skincare, cleaning, organization, fitness",
      duration: "15–18 seconds",
      script: `[BEFORE — 0-3s]\n[TEXT: "Before 😩"]\n[Show the problem state clearly]\n\n[PRODUCT — 3-6s]\n[TEXT: "The fix:"]\n[Show product — clean shot]\n\n[APPLICATION — 6-11s]\n[Show product being used — quick but clear]\n[Voiceover: "One application. That's it."]\n\n[AFTER — 11-15s]\n[TEXT: "After ✨"]\n[Show the result — same angle as before]\n[Voiceover: "Every. Single. Time."]\n\n[CTA — 15-17s]\n[TEXT: "Save this 📌 | Link below"]`,
      why: "Before/after content is the most saved format on Pinterest after tutorials. The matching angles and clear labels make the transformation undeniable.",
      customization: "The before and after must be shot from the same angle. Use the same lighting. The only variable should be the product's effect.",
    },
  ],
  tips: [
    { title: "Design for silent viewing", text: "Pinterest is a quiet platform. Most users browse without sound. Every key message must be communicated through text overlays and visual storytelling. Sound is a bonus, not a requirement." },
    { title: "Optimize for saves, not just clicks", text: "Saves are Pinterest's most valuable engagement signal. Content that gets saved gets shown to more people. Include \"Save this\" in your CTA — it directly drives the metric that matters." },
    { title: "Use Pinterest SEO in titles and descriptions", text: "Pinterest is a search engine. Include your target keywords in the Pin title and description. \"Glass skin routine\" will get found; \"My morning routine\" won't." },
    { title: "Use 2:3 aspect ratio for standard Pins", text: "2:3 (1000×1500px) takes up the most real estate in the Pinterest feed. It's the optimal format for visibility. Use 9:16 for Idea Pins specifically." },
    { title: "Seasonal content performs 45 days early", text: "Pinterest users plan ahead. Holiday content should go live 45 days before the holiday. Summer content in April. Back-to-school in June. Plan your content calendar accordingly." },
  ],
  dos: [
    "Use 2:3 aspect ratio for maximum feed visibility",
    "Add text overlays for every key message — Pinterest is a silent platform",
    "Include keywords in Pin titles and descriptions for search discovery",
    "Use warm, well-lit, aesthetically pleasing visuals",
    "Include \"Save this\" in your CTA — saves drive the algorithm",
    "Plan seasonal content 45 days in advance",
  ],
  donts: [
    "Don't use dark, low-quality, or cluttered visuals — Pinterest is an aesthetic platform",
    "Don't rely on sound to communicate your message",
    "Don't use TikTok-style chaotic editing — Pinterest audiences prefer calm, intentional pacing",
    "Don't ignore Pinterest SEO — it's a search engine, not just a social platform",
    "Don't use horizontal video — vertical (2:3 or 9:16) dominates on Pinterest",
    "Don't forget the \"Save\" CTA — it's the most important engagement action on Pinterest",
  ],
  ctaLine: "Create Pinterest video ads that get saved and convert. No camera needed.",
};
export default data;
