import type { PlatformPageData } from "./_shared";

const data: PlatformPageData = {
  platform: "X (Twitter)",
  h1: "AI Video Ads for X (Twitter): Short-Form UGC Strategy (2026)",
  verified: "March 2026",
  meta: "Create AI video ads for X (Twitter) — exact specs, 3 scripts for promoted video, and the UGC strategy that drives engagement and conversions on X in 2026.",
  intro: "X (formerly Twitter) has leaned hard into video — video posts get 10x more engagement than text-only tweets. The platform's ad environment is unique: ads appear in the timeline alongside real-time conversations, news, and opinions. UGC-style video ads that feel like someone sharing a genuine take outperform polished brand content by 1.8x on engagement rate. The key is matching X's conversational, opinion-driven culture. This guide covers specs, formats, and scripts for video ads on X.",
  specs: [
    { label: "Aspect ratio", value: "16:9 (landscape), 1:1 (square), 9:16 (vertical). 1:1 recommended" },
    { label: "Resolution", value: "1200×1200 (1:1), 1920×1080 (16:9), 1080×1920 (9:16)" },
    { label: "Video duration", value: "Max 2:20 for ads. Sweet spot: 6–15 seconds" },
    { label: "Max file size", value: "1 GB" },
    { label: "File formats", value: ".mp4, .mov" },
    { label: "Sound", value: "Optional — many X users scroll with sound off" },
    { label: "Captions", value: "Strongly recommended — burned-in for silent scrolling" },
    { label: "Tweet copy", value: "280 characters. First 100 characters visible without expanding" },
    { label: "Website card", value: "Headline (70 chars) + description (optional) + URL" },
    { label: "Autoplay", value: "Videos autoplay muted in timeline" },
  ],
  formats: [
    {
      name: "The Hot Take",
      why: "X is built on opinions. A video that opens with a bold, slightly contrarian take on an industry topic gets engagement because people want to agree, disagree, or share. This format turns your ad into a conversation starter.",
      structure: [
        { time: "0–2s", desc: "Bold claim — \"[Common practice] is a waste of money. Here's why.\"" },
        { time: "2–8s", desc: "Back it up — quick evidence or reasoning" },
        { time: "8–12s", desc: "Your alternative — introduce your product as the better approach" },
        { time: "12–15s", desc: "CTA — \"Link below\" or \"Try it yourself\"" },
      ],
      length: "12–18 seconds",
      firstFrame: "Person speaking with conviction. Text overlay with the hot take.",
    },
    {
      name: "The Quick Proof",
      why: "X users are skeptical. They've seen every marketing claim. A video that leads with proof — a result, a metric, a before/after — earns credibility before asking for anything.",
      structure: [
        { time: "0–2s", desc: "Result first — \"[Specific metric] in [timeframe]. Here's how.\"" },
        { time: "2–6s", desc: "Brief explanation — what you did and what tool you used" },
        { time: "6–10s", desc: "Show the proof — screenshot, demo, or visual result" },
        { time: "10–12s", desc: "CTA — \"Link in bio\" or website card" },
      ],
      length: "10–15 seconds",
      firstFrame: "Text overlay with the headline metric. Grabs attention in a fast-scrolling feed.",
    },
    {
      name: "The Thread Teaser",
      why: "X users love threads. A short video that teases a longer story or breakdown drives clicks to your profile or website. It leverages X's native content format as an ad hook.",
      structure: [
        { time: "0–2s", desc: "Teaser — \"I spent [time] testing [category]. Here's what I found...\"" },
        { time: "2–6s", desc: "Top-level findings — 2–3 key insights, rapid-fire" },
        { time: "6–8s", desc: "Cliffhanger — \"But the biggest surprise was...\"" },
        { time: "8–10s", desc: "CTA — \"Full breakdown in the link below\"" },
      ],
      length: "8–12 seconds",
      firstFrame: "Person speaking or text overlay with the teaser headline.",
    },
  ],
  scripts: [
    {
      name: "The Contrarian Take",
      bestFor: "SaaS, B2B, any product challenging the status quo",
      duration: "14–18 seconds",
      script: `[HOOK — 0-2s]\n"Unpopular opinion: [common industry practice] is\nthe reason your [metric] is terrible."\n[Direct to camera, confident]\n\n[EXPLAIN — 2-10s]\n"Everyone does [common approach] because it's what\nthe gurus teach. But the data says otherwise.\n[Specific stat or evidence]. The brands winning\nright now are doing [alternative approach]."\n\n[BRIDGE — 10-14s]\n"That's exactly what [product] is built for.\n[One-line value prop]."\n\n[CTA — 14-16s]\n"Link below. Or quote tweet me if you disagree."`,
      why: "\"Quote tweet me if you disagree\" is genius on X — it drives engagement whether people agree or not. Engagement boosts the ad's visibility. The contrarian hook matches X's debate culture.",
      customization: "The take must be defensible. X users will challenge you in replies. If your contrarian claim falls apart under scrutiny, it backfires.",
    },
    {
      name: "The Result Flex",
      bestFor: "Products with measurable outcomes, any audience",
      duration: "10–14 seconds",
      script: `[HOOK — 0-2s]\n"[Specific result] in [timeframe]. Not a theory —\nhere's the proof."\n[Show metric or result immediately]\n\n[HOW — 2-8s]\n"I used [product] to [what you did]. Took [time to\nset up]. Cost [price]. The result: [metric before]\n→ [metric after]."\n\n[CTA — 8-12s]\n"Link below if you want the same result.\nNo catch. Just works."`,
      why: "Leading with the result and backing it with specifics is the most credible format on X. The platform's audience is data-driven and skeptical — proof first, pitch second.",
      customization: "Use real numbers. Rounded numbers feel fake on X. \"43% improvement\" beats \"50% improvement\" every time.",
    },
    {
      name: "The Teaser Hook",
      bestFor: "Content marketing, driving traffic to longer content",
      duration: "8–10 seconds",
      script: `[HOOK — 0-2s]\n"I tested [number] [tools/methods/products] for\n[purpose]. The results surprised me."\n[Direct to camera or text on screen]\n\n[TEASE — 2-6s]\n"[Tool 1] was overrated. [Tool 2] was underrated.\nAnd the winner wasn't even close."\n\n[CTA — 6-9s]\n"Full breakdown → link below.\nSpoiler: it's not the one you'd expect."`,
      why: "The teaser format exploits curiosity. X users who see \"the results surprised me\" need to know the answer. The spoiler tease in the CTA adds another curiosity layer.",
      customization: "You must deliver on the tease. If the linked content doesn't match the promise, you'll get ratio'd in the replies.",
    },
  ],
  tips: [
    { title: "Keep it under 15 seconds", text: "X is the fastest-scrolling platform. Videos under 15 seconds see 2.5x higher completion rates. Get to the point immediately — no intros, no warm-ups." },
    { title: "Write strong tweet copy", text: "The tweet text above your video matters as much as the video itself. Use the first 100 characters to hook — that's what's visible without expanding." },
    { title: "Encourage replies and quote tweets", text: "X's algorithm rewards engagement. Ads that generate replies and quote tweets get shown to more people. Ask questions, make bold claims, invite debate." },
    { title: "Use website cards for conversion", text: "Attach a website card to your promoted video for a clickable CTA below the video. This drives 2x more clicks than relying on a link in the tweet text." },
    { title: "Target by conversation topics", text: "X's conversation targeting lets you reach people discussing specific topics. Target conversations about your competitors, your industry, or problems your product solves." },
  ],
  dos: [
    "Use 1:1 aspect ratio for maximum timeline visibility",
    "Keep videos under 15 seconds for best completion rates",
    "Add burned-in captions — X autoplays muted",
    "Write compelling tweet copy — it's half the ad",
    "Encourage engagement — replies and quote tweets boost distribution",
    "Use website cards for clickable CTAs",
  ],
  donts: [
    "Don't use long-form video — X users scroll fast",
    "Don't ignore the tweet copy — a great video with weak copy underperforms",
    "Don't use soft, vague messaging — X rewards bold, specific claims",
    "Don't make claims you can't defend — X users will challenge you publicly",
    "Don't use the same creative as Instagram — X has a different culture and tone",
    "Don't forget to monitor replies — negative engagement can spiral on X",
  ],
  ctaLine: "Create video ads for X that spark conversation and convert. No camera needed.",
};
export default data;
