import type { PlatformPageData } from "./_shared";

const data: PlatformPageData = {
  platform: "WhatsApp",
  h1: "AI Video Content for WhatsApp Marketing (2026)",
  verified: "March 2026",
  meta: "Create AI video content for WhatsApp marketing — specs, 3 message scripts, broadcast strategy, and how to use video in WhatsApp Business campaigns.",
  intro: "WhatsApp has 2B+ monthly active users and the highest open rate of any messaging channel — 98% compared to 20% for email. Video messages on WhatsApp get 3x more engagement than text-only messages. For brands using WhatsApp Business API for marketing, customer support, and post-purchase engagement, video content is the highest-performing format. The key difference from social ads: WhatsApp is personal. Videos need to feel like they're from a person, not a brand. This guide covers how to create video content optimized for WhatsApp marketing.",
  specs: [
    { label: "Aspect ratio", value: "9:16 (vertical, recommended) or 1:1 (square)" },
    { label: "Resolution", value: "720×1280 minimum. 1080×1920 recommended" },
    { label: "Video duration", value: "Max 16 MB file size. Sweet spot: 15–30 seconds" },
    { label: "Max file size", value: "16 MB (WhatsApp compression limit)" },
    { label: "File formats", value: ".mp4 (H.264 video, AAC audio)" },
    { label: "Sound", value: "Required — WhatsApp videos play with sound when tapped" },
    { label: "Captions", value: "Recommended — some users preview without sound" },
    { label: "Thumbnail", value: "Auto-generated from first frame — make it compelling" },
    { label: "Message text", value: "Accompany video with a short text message for context" },
    { label: "CTA", value: "Include clickable link in the message text below the video" },
  ],
  formats: [
    {
      name: "The Personal Message",
      why: "WhatsApp is a personal messaging app. Video that feels like a personal message from a real person gets watched and responded to. This format mimics a friend sending you a video recommendation.",
      structure: [
        { time: "0–2s", desc: "Greeting — \"Hey! I wanted to share something with you...\"" },
        { time: "2–10s", desc: "Message — the recommendation, update, or offer in conversational tone" },
        { time: "10–18s", desc: "Details — specific information the recipient needs" },
        { time: "18–22s", desc: "CTA — \"Tap the link below to [action]\"" },
      ],
      length: "18–25 seconds",
      firstFrame: "Person looking at camera, friendly expression. Feels like a video message.",
    },
    {
      name: "The Product Update",
      why: "For post-purchase engagement and upselling, a quick video showing a new product, feature, or offer feels more personal than an email blast. WhatsApp's intimate context makes the recommendation feel genuine.",
      structure: [
        { time: "0–2s", desc: "Hook — \"Quick update for you...\" or \"You're going to love this...\"" },
        { time: "2–8s", desc: "Show the new product/feature/offer" },
        { time: "8–12s", desc: "Why it matters to them specifically" },
        { time: "12–15s", desc: "CTA — \"Tap below to check it out\"" },
      ],
      length: "12–18 seconds",
      firstFrame: "Person or product visible. Warm, personal tone.",
    },
    {
      name: "The Thank You Video",
      why: "Post-purchase thank you videos on WhatsApp have 85%+ open rates and drive repeat purchases. A personal video thanking the customer and suggesting a complementary product feels genuine and drives loyalty.",
      structure: [
        { time: "0–3s", desc: "Thank you — \"Hey! Just wanted to say thank you for your order...\"" },
        { time: "3–10s", desc: "Value add — a tip for using the product, or what to expect" },
        { time: "10–15s", desc: "Suggestion — \"If you love [product], you might also like [upsell]\"" },
        { time: "15–18s", desc: "Close — \"Let me know if you have any questions!\"" },
      ],
      length: "15–20 seconds",
      firstFrame: "Smiling person, warm setting. Feels like a personal thank you.",
    },
  ],
  scripts: [
    {
      name: "The Welcome Message",
      bestFor: "New subscribers, post-opt-in engagement",
      duration: "18–22 seconds",
      script: `[GREETING — 0-3s]\n"Hey! Welcome — I'm so glad you're here."\n[Warm, direct to camera, personal]\n\n[VALUE — 3-12s]\n"I'm going to be sharing [what they'll get] with you\nhere on WhatsApp. Things like [benefit 1], [benefit 2],\nand exclusive [offers/content] you won't find anywhere\nelse."\n\n[NEXT STEP — 12-18s]\n"To get started, [specific action — check the link\nbelow / reply with your [preference] / etc.]."\n\n[CLOSE — 18-20s]\n"Talk soon! And feel free to reply anytime —\nI actually read these."`,
      why: "A video welcome message sets the tone for the entire WhatsApp relationship. It feels personal, builds trust, and drives the first engagement action. \"I actually read these\" humanizes the brand.",
      customization: "The welcome should match your brand voice. Casual for DTC, slightly more professional for B2B. The key is warmth — WhatsApp is personal territory.",
    },
    {
      name: "The Flash Offer",
      bestFor: "Promotions, limited-time offers, existing customers",
      duration: "12–15 seconds",
      script: `[HOOK — 0-2s]\n"Quick heads up — this is only for the next [timeframe]"\n[Urgent but friendly tone]\n\n[OFFER — 2-8s]\n"We're doing [specific offer] on [product/category].\nThat's [value proposition — savings amount, bonus,\nexclusive access]. Only for WhatsApp subscribers."\n\n[CTA — 8-12s]\n"Tap the link below before [deadline].\nThis won't last."\n[Point down toward link area]`,
      why: "WhatsApp's 98% open rate makes it the best channel for time-sensitive offers. The \"only for WhatsApp subscribers\" exclusivity rewards the opt-in and drives action.",
      customization: "The urgency must be real. Fake scarcity erodes trust on a personal channel like WhatsApp. If the offer is genuinely limited, say so. If not, use a different angle.",
    },
    {
      name: "The Post-Purchase Thank You",
      bestFor: "Customer retention, upselling, loyalty",
      duration: "16–20 seconds",
      script: `[THANK YOU — 0-3s]\n"Hey! Your order just shipped and I wanted to\npersonally say thank you."\n[Genuine, warm, personal]\n\n[TIP — 3-10s]\n"Quick tip: when you get [product], [usage tip that\nimproves the experience]. It makes a huge difference."\n\n[UPSELL — 10-15s]\n"Also — a lot of people who love [product] also grab\n[complementary product]. If you're interested, I put\na link below with [incentive]."\n\n[CLOSE — 15-18s]\n"Thanks again! Reply here if you need anything.\nI'm always around."`,
      why: "Post-purchase video messages drive 2–3x higher repeat purchase rates than email. The usage tip adds genuine value. The upsell feels like a recommendation, not a pitch.",
      customization: "The usage tip must be genuinely helpful. If the customer feels like the video added value, they'll be receptive to the upsell. If it feels like pure selling, they'll mute the channel.",
    },
  ],
  tips: [
    { title: "Keep file size under 16 MB", text: "WhatsApp compresses videos over 16 MB, which destroys quality. Optimize your video to stay under the limit: 720p resolution, H.264 encoding, 15–30 seconds duration." },
    { title: "Make it feel personal, not broadcast", text: "WhatsApp is a personal messaging app. Videos that feel like mass marketing get ignored or reported. Use first-person language, direct eye contact, and conversational tone." },
    { title: "Include a text message with the video", text: "Always pair your video with a short text message that provides context and includes a clickable link. The text message is where your CTA link lives." },
    { title: "Respect opt-in and frequency", text: "WhatsApp marketing requires explicit opt-in. Don't send more than 2–3 video messages per week. Over-messaging leads to blocks and reports, which can get your number banned." },
    { title: "Use WhatsApp Business API for scale", text: "For broadcast campaigns, use the WhatsApp Business API (through providers like Twilio, MessageBird, or WATI). The regular WhatsApp Business app has broadcast limits." },
  ],
  dos: [
    "Keep videos under 16 MB to avoid compression",
    "Use vertical (9:16) format for mobile viewing",
    "Make videos feel personal — first person, eye contact, conversational",
    "Include a text message with context and a clickable link",
    "Respect opt-in consent and message frequency limits",
    "Add a usage tip or genuine value to every marketing video",
  ],
  donts: [
    "Don't send videos that feel like mass marketing — WhatsApp is personal",
    "Don't exceed 2–3 video messages per week — over-messaging gets you blocked",
    "Don't skip the text message — the video alone doesn't have a clickable CTA",
    "Don't use horizontal video — WhatsApp is a mobile-first platform",
    "Don't send without opt-in consent — WhatsApp enforces this strictly",
    "Don't use the same creative as social ads — WhatsApp requires a personal touch",
  ],
  ctaLine: "Create personal video messages for WhatsApp marketing. No camera needed.",
};
export default data;
