import type { PlatformPageData } from "./_shared";

const data: PlatformPageData = {
  platform: "YouTube Pre-Roll",
  h1: "AI Video Ads for YouTube Pre-Roll & In-Stream (2026)",
  verified: "March 2026",
  meta: "Create AI video ads for YouTube pre-roll and in-stream placements — exact specs, 3 scripts optimized for skippable and non-skippable formats, and strategy for 2026.",
  intro: "YouTube pre-roll and in-stream ads reach viewers who are actively watching content — not passively scrolling. That's a fundamentally different attention state, and it changes everything about how your ad should be structured. The challenge: viewers can skip after 5 seconds on skippable ads, and they will unless your opening is compelling. UGC-style pre-roll ads see 28% higher view-through rates than polished brand spots because they feel like content, not interruptions. This guide covers specs, formats, and scripts for both skippable and non-skippable YouTube ad placements.",
  specs: [
    { label: "Aspect ratio", value: "16:9 (landscape) or 1:1 (square). 16:9 recommended for pre-roll" },
    { label: "Resolution", value: "1920×1080px (1080p) recommended. Min: 640×360" },
    { label: "Skippable in-stream", value: "12 seconds–3 minutes. Skip available after 5 seconds" },
    { label: "Non-skippable in-stream", value: "15 or 20 seconds max" },
    { label: "Bumper ads", value: "6 seconds max, non-skippable" },
    { label: "Max file size", value: "256 MB" },
    { label: "File formats", value: ".mp4, .mov, .avi, .webm" },
    { label: "Sound", value: "Required — YouTube pre-roll plays with sound" },
    { label: "Companion banner", value: "300×60px optional display banner alongside the ad" },
    { label: "CTA overlay", value: "Auto-placed by Google Ads — headline + description + URL" },
  ],
  formats: [
    {
      name: "The 5-Second Hook (Skippable)",
      why: "You have exactly 5 seconds before the skip button appears. This format front-loads the most compelling element — a bold claim, a surprising stat, or an emotional hook — so viewers choose to keep watching.",
      structure: [
        { time: "0–5s", desc: "The un-skippable hook — your single most compelling statement or visual" },
        { time: "5–15s", desc: "Deliver on the hook — explain, demonstrate, or prove it" },
        { time: "15–25s", desc: "Product introduction — naturally bridge from the hook to your solution" },
        { time: "25–30s", desc: "CTA — clear next step with urgency or value proposition" },
      ],
      length: "25–35 seconds",
      firstFrame: "Face speaking directly to camera or bold text with a surprising claim.",
    },
    {
      name: "The Non-Skip Testimonial",
      why: "Non-skippable 15-second ads guarantee full viewership. A tight testimonial that delivers problem-solution-result in 15 seconds is the most efficient use of guaranteed attention.",
      structure: [
        { time: "0–3s", desc: "Hook + problem — \"I was spending $X on [problem] and getting nowhere\"" },
        { time: "3–9s", desc: "Solution + result — \"Then I tried [product] and [specific outcome]\"" },
        { time: "9–13s", desc: "Proof — show the result or share a specific metric" },
        { time: "13–15s", desc: "CTA — \"Try it free\" or \"Link below\"" },
      ],
      length: "15 seconds exactly",
      firstFrame: "Person speaking with genuine frustration or surprise — emotional opening.",
    },
    {
      name: "The 6-Second Bumper",
      why: "Bumper ads are 6 seconds, non-skippable, and designed for brand recall. One message, one visual, one CTA. No story arc — just impact.",
      structure: [
        { time: "0–2s", desc: "Bold statement or question — text on screen + voiceover" },
        { time: "2–4s", desc: "Product shot or quick demo" },
        { time: "4–6s", desc: "Brand name + CTA" },
      ],
      length: "6 seconds exactly",
      firstFrame: "Bold text or product in motion. Every frame must earn its place.",
    },
  ],
  scripts: [
    {
      name: "The Skippable Hook",
      bestFor: "Any product, cold audiences, awareness + consideration campaigns",
      duration: "28–35 seconds",
      script: `[HOOK — 0-5s]\n"You're about to skip this ad. But if you're spending\nmore than $50/month on [category], you need to hear\nthis first."\n[Direct to camera, confident, slightly urgent]\n\n[DELIVER — 5-18s]\n"Most people waste money on [common approach] because\nthey don't realize [insight]. I switched to [product]\n[timeframe] ago and [specific result]. Not a small\ndifference — [quantified improvement]."\n\n[PROOF — 18-25s]\n"Here's what that looks like: [show result, share\nmetric, or describe the change]. And I'm paying\n[price comparison] for it."\n\n[CTA — 25-30s]\n"Click the link below to try it. If you're still\noverpaying for [category], this is your sign to stop."`,
      why: "Acknowledging the skip button disarms the viewer. \"You're about to skip\" is a pattern interrupt — it's unexpected in an ad. The $50/month qualifier targets the right audience and gives a reason to keep watching.",
      customization: "The 5-second hook is everything. Test 3–5 different hooks with the same body. The hook that keeps the most viewers past the skip button wins.",
    },
    {
      name: "The 15-Second Testimonial",
      bestFor: "Non-skippable placement, retargeting, bottom-funnel",
      duration: "15 seconds exactly",
      script: `[HOOK — 0-3s]\n"I tried [product] expecting nothing and it actually\n[surprising result]."\n[Direct to camera, genuine surprise]\n\n[STORY — 3-10s]\n"I've been dealing with [problem] for [timeframe].\n[Product] fixed it in [shorter timeframe]. My\n[specific metric] went from [before] to [after]."\n\n[CTA — 10-15s]\n"Click below to try it. Seriously — I wish I'd\nfound this sooner."\n[Product visible, point to CTA area]`,
      why: "15 seconds, no skip option, guaranteed attention. Every word must earn its place. The specific before/after metric is the proof that makes it credible.",
      customization: "Read the script out loud and time it. If it's over 15 seconds, cut words. Non-skippable ads have zero tolerance for going over.",
    },
    {
      name: "The 6-Second Bumper",
      bestFor: "Brand recall, retargeting, frequency campaigns",
      duration: "6 seconds exactly",
      script: `[0-2s]\n[TEXT ON SCREEN: "Still paying $300 for one UGC video?"]\n[Quick cut]\n\n[2-4s]\n[TEXT ON SCREEN: "Try $4.90"]\n[Show product/interface briefly]\n\n[4-6s]\n[TEXT ON SCREEN: "members.mom"]\n[Logo + "Get Started"]`,
      why: "6 seconds. One comparison. One price anchor. One brand name. Bumper ads aren't for conversion — they're for planting a seed that your longer ads can harvest.",
      customization: "Pick your single strongest selling point. Price comparison, speed comparison, or result comparison. One message only.",
    },
  ],
  tips: [
    { title: "Win the first 5 seconds or lose everything", text: "On skippable ads, 65–80% of viewers skip at the 5-second mark. Your hook must be so compelling that skipping feels like missing out. Test hooks obsessively." },
    { title: "Use bumper ads for retargeting", text: "Show 6-second bumpers to people who watched 50%+ of your skippable ad. The bumper reinforces the message and drives the click. This sequence consistently outperforms either format alone." },
    { title: "Landscape for pre-roll, vertical for Shorts", text: "Pre-roll plays before landscape YouTube videos. Using 16:9 format matches the viewing context. Don't use vertical video for pre-roll — it looks out of place." },
    { title: "Include a companion banner", text: "The 300×60px companion banner appears next to your video ad on desktop. It's free real estate — use it for your brand name, offer, and CTA." },
    { title: "Bid on view-through, not impressions", text: "For skippable ads, use Target CPV (cost per view) bidding. You only pay when someone watches 30 seconds or the full ad. This naturally optimizes for engaging creative." },
  ],
  dos: [
    "Use 16:9 landscape for pre-roll and in-stream placements",
    "Front-load your most compelling content in the first 5 seconds",
    "Include clear audio — YouTube pre-roll always plays with sound",
    "Add a companion banner for desktop viewers",
    "Use frequency capping to prevent ad fatigue",
    "Sequence bumper ads after skippable ads for retargeting",
  ],
  donts: [
    "Don't use vertical video for pre-roll — save 9:16 for Shorts",
    "Don't save your best content for after the 5-second mark on skippable ads",
    "Don't exceed 15 seconds on non-skippable ads — the system will reject it",
    "Don't use the same creative for pre-roll and Shorts — they're different contexts",
    "Don't ignore the companion banner — it's free additional visibility",
    "Don't run pre-roll without frequency capping — overexposure kills performance",
  ],
  ctaLine: "Create YouTube pre-roll ads that survive the skip button. No studio needed.",
};
export default data;
