import type { GlossaryPageData } from "./_shared";

const data: GlossaryPageData = {
  term: "AI Actor",
  h1: "What Is an AI Actor? How Synthetic Performers Work",
  meta: "An AI actor is a synthetic performer generated by artificial intelligence to appear in videos. Learn how AI actors differ from avatars, their use cases, and ethical considerations.",
  definition: "An AI actor is a fully synthetic on-screen performer created using artificial intelligence. Unlike AI avatars (which are typically based on real people's likenesses), AI actors can be entirely fictional — generated from scratch or composited from multiple reference faces. They perform in videos, ads, and presentations with realistic speech, expressions, and movement.",
  whyMatters: [
    { label: "No talent contracts or usage rights", text: "When you hire a human actor, you negotiate usage rights, exclusivity windows, and renewal fees. AI actors have none of these constraints. You own the output, use it wherever you want, for as long as you want, without residuals or renegotiations. For brands running ads across 10+ markets, this simplifies legal and reduces ongoing costs significantly." },
    { label: "Infinite casting options", text: "Need a 30-year-old fitness enthusiast for your supplement ad and a 55-year-old professional for your financial services spot? AI actors let you cast the perfect presenter for every audience segment without maintaining a roster of human talent. You can match the performer to the demographic you're targeting." },
    { label: "Always available, always consistent", text: "Human actors get sick, age, change their look, or become controversial. AI actors are permanently available and permanently consistent. This matters for brands building long-running campaigns where the presenter becomes associated with the product." },
  ],
  howItWorks: [
    { heading: "Generation Methods", text: "AI actors are created through two primary methods. The first is likeness-based: a real person consents to have their appearance digitized, and the AI generates new performances based on their face and voice. The second is fully synthetic: generative AI creates a face that doesn't belong to any real person, trained on broad datasets of human features. Both methods produce video-ready performers, but fully synthetic actors avoid likeness rights issues entirely." },
    { heading: "Performance Quality", text: "Modern AI actors can deliver nuanced performances — subtle smiles, raised eyebrows, natural pauses, and conversational pacing. The technology has moved well beyond the robotic talking heads of 2022. Current-generation AI actors are difficult to distinguish from real people in short-form video formats, especially when combined with high-quality text-to-speech and professional scripts." },
  ],
  example: "A global CPG brand needs testimonial-style ads for 8 different markets. Each market needs a presenter who looks like the local demographic and speaks the local language. Casting 8 human actors across 8 countries would cost $40,000+ and take 6 weeks. Using AI actors, they generate 8 market-specific videos in 2 days for under $800. When the campaign messaging changes quarterly, they re-render all 8 videos in an afternoon.",
  product: {
    intro: "ReUGC provides AI actors purpose-built for performance advertising:",
    points: [
      "Diverse performer library — Access AI actors spanning different ages, ethnicities, and presentation styles. Match your performer to your target audience for every campaign without casting calls or talent fees.",
      "Full commercial rights included — Every video you generate with ReUGC is yours to use across any platform, any market, for any duration. No usage rights negotiations, no exclusivity conflicts. Plans from $49/mo.",
      "Performance-tested delivery — ReUGC AI actors are optimized for the casual, authentic delivery style that converts on social platforms. They don't look like corporate spokespeople — they look like real people sharing genuine opinions.",
    ],
  },
  related: [
    { term: "AI Avatar", slug: "ai-avatar" },
    { term: "Digital Human", slug: "digital-human" },
    { term: "Deepfake", slug: "deepfake" },
    { term: "AI Voice Cloning", slug: "voice-cloning" },
    { term: "AI Lip Sync", slug: "lip-sync-ai" },
    { term: "AI UGC", slug: "ai-ugc" },
  ],
  relatedNote: "AI actors overlap significantly with AI avatars and digital humans — the distinctions are subtle but matter for licensing and ethics. AI actors rely on voice cloning and lip-sync technology to deliver realistic performances, and they're a core component of the AI UGC pipeline.",
};
export default data;
