import type { GlossaryPageData } from "./_shared";

const data: GlossaryPageData = {
  term: "CPM",
  h1: "What Is CPM? Cost Per Mille for Video Ads",
  meta: "CPM (cost per mille) is the cost of 1,000 ad impressions. Learn how CPM works, what affects it, and how to lower your CPM through better creative.",
  definition: "CPM (cost per mille) is the price an advertiser pays for 1,000 impressions of their ad. 'Mille' is Latin for thousand. If your CPM is $10, you're paying $10 every time your ad is shown 1,000 times. CPM is the foundational cost metric in digital advertising — it determines how far your budget stretches and how many people see your message.",
  whyMatters: [
    { label: "It's the base cost of attention", text: "Every other metric in your ad funnel is built on top of CPM. Your CPA is a function of CPM × (1/CTR) × (1/conversion rate). If your CPM doubles, your CPA doubles — unless you can compensate with better CTR or conversion rates. Understanding and optimizing CPM is understanding the economics of your entire paid acquisition strategy." },
    { label: "Creative quality directly affects CPM", text: "Platform algorithms use engagement signals (watch time, clicks, shares) to determine ad relevance. Ads with higher engagement get lower CPMs because the platform wants to show content users enjoy. A UGC-style video with a 40% thumb-stop rate might get a $7 CPM, while a generic brand ad with a 15% thumb-stop rate pays $14 for the same audience. Better creative literally costs less to distribute." },
    { label: "CPM varies wildly by context", text: "CPM is influenced by platform (TikTok is generally cheaper than Meta), time of year (Q4 CPMs spike 40–80% due to holiday competition), audience (broad targeting is cheaper than narrow), placement (Stories vs. Feed vs. Reels), and industry (finance and insurance CPMs are 3–5x higher than apparel). Knowing your baseline CPM and what drives it up or down is essential for budget planning." },
  ],
  howItWorks: [
    { heading: "How CPM Is Determined", text: "CPM is set through real-time auction. When your ad is eligible to appear, it competes against other advertisers targeting the same user. The auction considers your bid, your ad's predicted engagement rate, and the estimated action rate (likelihood the user will take your desired action). Higher predicted engagement = lower CPM, because the platform earns more from ads users interact with. This is why creative quality is the most effective CPM lever." },
    { heading: "CPM vs. Other Cost Metrics", text: "CPM measures the cost of visibility. CPC (cost per click) measures the cost of engagement. CPA measures the cost of conversion. A low CPM with a low CTR means you're getting cheap impressions but nobody's clicking — you're paying less but getting less. The goal isn't the lowest CPM in isolation; it's the lowest CPA, which requires balancing CPM with CTR and conversion rate." },
  ],
  example: "Two competing e-commerce brands target the same audience on Meta during Black Friday. Brand A runs polished studio ads with a 16% thumb-stop rate and pays $18 CPM. Brand B runs UGC-style video ads with a 38% thumb-stop rate and pays $11 CPM. With identical $5,000 daily budgets, Brand B gets 454,545 impressions versus Brand A's 277,778 — 64% more eyeballs for the same spend. Brand B's higher engagement also earns better placement in the feed, compounding the advantage.",
  product: {
    intro: "ReUGC helps lower your CPM by producing the engaging, native-looking content that algorithms reward:",
    points: [
      "Native-format content gets lower CPMs — UGC-style videos generated by ReUGC look like organic content, which platforms reward with better relevance scores and lower auction prices.",
      "Fresh creative fights CPM inflation — As ads fatigue, engagement drops and CPMs rise. Regular creative refreshes from ReUGC keep engagement high and CPMs stable throughout your campaign lifecycle.",
      "Volume without budget strain — Generate 10–60 videos per month ($49–$199/mo) and always have fresh creative ready to deploy when CPMs start creeping up on your current ads.",
    ],
  },
  related: [
    { term: "CPA", slug: "cpa" },
    { term: "CTR", slug: "ctr" },
    { term: "ROAS", slug: "roas" },
    { term: "Ad Spend", slug: "ad-spend" },
    { term: "Thumb-Stop Rate", slug: "thumb-stop-rate" },
    { term: "Creative Fatigue", slug: "creative-fatigue" },
  ],
  relatedNote: "CPM is the cost foundation that CPA, CTR, and ROAS are built upon. It's directly improved by higher thumb-stop rates (which signal engagement to the algorithm) and directly worsened by creative fatigue (which tanks engagement and raises auction prices). Managing CPM is really about managing creative quality.",
};
export default data;
