import type { GlossaryPageData } from "./_shared";

const data: GlossaryPageData = {
  term: "Paid Social",
  h1: "What Is Paid Social? Advertising on Social Platforms",
  meta: "Paid social is advertising on social media platforms like Meta, TikTok, and YouTube. Learn how paid social works, which platforms to prioritize, and how to create effective paid social content.",
  definition: "Paid social is the practice of running paid advertisements on social media platforms — including Facebook, Instagram, TikTok, YouTube, Snapchat, Pinterest, and LinkedIn. Unlike organic social (posting content for free), paid social uses the platform's ad system to guarantee reach, target specific audiences, and drive measurable business outcomes like purchases, leads, or app installs.",
  whyMatters: [
    { label: "Organic reach is effectively dead", text: "On Facebook, organic posts reach 2–5% of your followers. On Instagram, it's 5–10%. On TikTok, organic reach is better but unpredictable. Paid social guarantees your content reaches your target audience at the scale you choose. For brands that need predictable, scalable customer acquisition, paid social is the primary channel." },
    { label: "The targeting is unmatched", text: "Social platforms have the richest user data on the internet — interests, behaviors, demographics, purchase history, and lookalike modeling. This data lets you put your ad in front of exactly the right people. Even with post-iOS 14.5 privacy changes, social platforms' first-party data and AI-driven optimization make them the most efficient paid channels for most consumer brands." },
    { label: "Creative format drives results", text: "Paid social is unique because ads appear in the same feed as organic content. This means your ads compete for attention not just against other ads, but against friends' posts, creator content, and entertainment. The ads that win are the ones that look and feel like native content — which is why UGC-style video has become the dominant format for paid social." },
  ],
  howItWorks: [
    { heading: "Platform Selection", text: "Each platform serves different audiences and objectives. Meta (Facebook + Instagram) offers the broadest reach and most mature optimization — it's the default for most brands. TikTok reaches younger audiences and rewards creative, entertaining content. YouTube captures high-intent viewers through search and pre-roll. Snapchat and Pinterest serve niche demographics with unique ad formats. Most brands start with Meta, add TikTok, and expand from there based on audience fit." },
    { heading: "Campaign Structure", text: "Paid social campaigns are organized in three layers: campaign (your objective — purchases, leads, awareness), ad set (your targeting, budget, and schedule), and ad (your creative). The creative layer is where most optimization happens in 2026 — platforms increasingly handle targeting automatically (like Meta's Advantage+), making the ad creative the primary variable that determines performance." },
  ],
  example: "A home goods brand launches on paid social with a $5,000/month budget split between Meta ($3,500) and TikTok ($1,500). On Meta, they run UGC-style video ads targeting broad audiences with Advantage+ shopping campaigns. On TikTok, they run Spark Ads using creator-style content. After 60 days, Meta delivers a $28 CPA and TikTok delivers a $22 CPA. They shift budget to 50/50 and increase total spend to $8,000/month, maintaining sub-$25 CPA across both platforms. The key insight: the same polished brand video that failed on both platforms was outperformed by simple, authentic-looking UGC content.",
  product: {
    intro: "ReUGC produces the native-looking video content that paid social platforms reward:",
    points: [
      "Platform-native content — Every video generated by ReUGC is designed to look like organic social content, not a polished ad. This native feel earns better engagement scores, lower CPMs, and higher CTRs across Meta and TikTok.",
      "Multi-platform ready — Generate videos in the vertical (9:16) format that works across TikTok, Instagram Reels, Facebook Reels, YouTube Shorts, and Snapchat. One production workflow, every platform covered.",
      "Creative volume for always-on campaigns — Paid social requires constant creative refreshes. ReUGC's plans ($49–$199/mo) ensure you always have fresh content ready to deploy across every platform.",
    ],
  },
  related: [
    { term: "Organic Social", slug: "organic-social" },
    { term: "Performance Marketing", slug: "performance-marketing" },
    { term: "UGC Ads", slug: "ugc-ads" },
    { term: "Meta Advantage+", slug: "advantage-plus" },
    { term: "TikTok Spark Ads", slug: "spark-ads" },
    { term: "Media Buying", slug: "media-buying" },
  ],
  relatedNote: "Paid social is the distribution channel; UGC ads are the dominant content format within it. Meta Advantage+ and TikTok Spark Ads are platform-specific tools that optimize paid social delivery. Media buying is the strategic discipline of managing paid social budgets across platforms. Organic social provides the content foundation that paid social amplifies.",
};
export default data;
