import type { PlatformPageData } from "./_shared";

const data: PlatformPageData = {
  platform: "Amazon",
  h1: "AI Video Ads for Amazon Sponsored Brands Video (2026)",
  verified: "March 2026",
  meta: "Create AI video ads for Amazon Sponsored Brands Video — exact specs, 3 scripts optimized for search results, and the strategy that drives clicks and sales on Amazon.",
  intro: "Amazon Sponsored Brands Video ads appear directly in search results — the highest-intent placement in all of e-commerce. When someone searches \"vitamin C serum\" on Amazon, they're ready to buy. A video ad in those results gets 2–3x higher click-through rates than static Sponsored Brands ads because video stops the scroll in a sea of product images. UGC-style video works especially well here: it looks like a real customer review, which is exactly what Amazon shoppers trust most. This guide covers specs, scripts, and strategy for Amazon video ads.",
  specs: [
    { label: "Aspect ratio", value: "16:9 (landscape, required for Sponsored Brands Video)" },
    { label: "Resolution", value: "1920×1080px (1080p) minimum. 1280×720 accepted" },
    { label: "Video duration", value: "6–45 seconds. Sweet spot: 15–30 seconds" },
    { label: "Max file size", value: "500 MB" },
    { label: "File formats", value: ".mp4, .mov" },
    { label: "Sound", value: "Optional — Amazon videos autoplay muted in search results" },
    { label: "Captions", value: "Required — videos play without sound by default" },
    { label: "Safe zone", value: "Avoid bottom 10% (mute/unmute button overlay)" },
    { label: "Looping", value: "Videos auto-loop — design ending to flow into beginning" },
    { label: "Text on screen", value: "Required for key messages — most viewers won't unmute" },
  ],
  formats: [
    {
      name: "The Product Review",
      why: "Amazon shoppers trust reviews above all else. A UGC-style video that looks like a real customer reviewing the product gets clicked because it provides the social proof shoppers are already looking for.",
      structure: [
        { time: "0–3s", desc: "Hook — \"I've been using this for [timeframe] — here's my honest review\"" },
        { time: "3–10s", desc: "Experience — what it's like to use the product, specific details" },
        { time: "10–18s", desc: "Result — what changed, with specific before/after" },
        { time: "18–22s", desc: "Verdict — \"Worth it\" or \"I'm on my second one\" + product visible" },
      ],
      length: "18–25 seconds",
      firstFrame: "Person holding the product. Product must be recognizable in the thumbnail.",
    },
    {
      name: "The Problem-Solution Demo",
      why: "Amazon shoppers search for solutions to problems. A video that names the problem, shows the product solving it, and proves the result matches the search intent perfectly.",
      structure: [
        { time: "0–2s", desc: "Problem — text overlay naming the exact problem the shopper searched for" },
        { time: "2–10s", desc: "Demo — show the product solving the problem in real-time" },
        { time: "10–15s", desc: "Result — show the outcome clearly" },
        { time: "15–18s", desc: "Product shot + key benefit text overlay" },
      ],
      length: "15–20 seconds",
      firstFrame: "Text overlay with the problem statement. Product visible.",
    },
    {
      name: "The Comparison Closer",
      why: "Amazon shoppers compare products. A video that acknowledges the comparison and positions your product as the winner saves the shopper research time — and earns the click.",
      structure: [
        { time: "0–3s", desc: "Hook — \"I tried [number] [product category] products. This one won.\"" },
        { time: "3–10s", desc: "Quick comparison — what others got wrong, what this gets right" },
        { time: "10–18s", desc: "Proof — show the product in use with the winning feature highlighted" },
        { time: "18–22s", desc: "CTA — \"Check the reviews\" or product shot with rating" },
      ],
      length: "18–25 seconds",
      firstFrame: "Multiple products visible or text overlay with comparison claim.",
    },
  ],
  scripts: [
    {
      name: "The Honest Review",
      bestFor: "Any Amazon product, search result placement",
      duration: "20–25 seconds",
      script: `[HOOK — 0-3s]\n[TEXT: "Honest review after 30 days"]\n[Person holding product]\n[Voiceover: "I've been using this for a month. Here's\nwhat I actually think."]\n\n[EXPERIENCE — 3-12s]\n[TEXT: Key features as bullet points appearing]\n[Voiceover: "The [feature 1] is [assessment]. The\n[feature 2] is [assessment]. And the [feature 3]\nis what really sets it apart — [specific detail]."]\n\n[RESULT — 12-18s]\n[TEXT: "The result:"]\n[Show result or describe outcome]\n[Voiceover: "[Specific result]. I wasn't expecting\nit to work this well."]\n\n[CLOSE — 18-22s]\n[TEXT: "⭐⭐⭐⭐⭐ Worth every penny"]\n[Product shot — clean, recognizable]\n[Voiceover: "Definitely worth it. Check the reviews."]`,
      why: "The \"honest review after 30 days\" hook matches what Amazon shoppers are looking for — real user experiences. Text overlays ensure the message works without sound. The star rating visual reinforces the review format.",
      customization: "The review must feel balanced. Mention one minor limitation (\"the packaging could be better\") to increase credibility. Perfect reviews feel fake.",
    },
    {
      name: "The Quick Demo",
      bestFor: "Products with visible use cases, search result placement",
      duration: "15–18 seconds",
      script: `[HOOK — 0-2s]\n[TEXT: "Watch this 👇"]\n[Product in hand, start using immediately]\n\n[DEMO — 2-10s]\n[Show product being used — quick, clear steps]\n[TEXT: Step-by-step labels]\n[Voiceover: "[Step 1]. [Step 2]. Done."]\n\n[RESULT — 10-14s]\n[Show the result clearly]\n[TEXT: "[Key benefit] ✓"]\n[Voiceover: "Works every time."]\n\n[CLOSE — 14-17s]\n[Product shot with price or key feature]\n[TEXT: "Check availability 👇"]`,
      why: "Amazon shoppers want to see the product in action before buying. A quick demo that shows exactly how it works and what the result looks like reduces purchase anxiety.",
      customization: "The demo must show the product being used for its primary purpose. Don't show secondary features — show the main reason someone would buy it.",
    },
    {
      name: "The Comparison Winner",
      bestFor: "Products in competitive categories",
      duration: "22–28 seconds",
      script: `[HOOK — 0-3s]\n[TEXT: "I tried 5 [product category]. Here's the winner."]\n[Multiple products visible or quick montage]\n\n[COMPARISON — 3-14s]\n[TEXT: Feature comparison appearing as list]\n[Voiceover: "Most [products] have [common limitation].\nThis one doesn't. [Key differentiator] plus\n[second differentiator]. And it's [price comparison]."]\n\n[PROOF — 14-20s]\n[Show the winning product in use]\n[TEXT: "The difference:"]\n[Voiceover: "[Specific result that proves it's better]"]\n\n[CLOSE — 20-24s]\n[Product shot — clean, prominent]\n[TEXT: "Best in category ✓"]\n[Voiceover: "Check the reviews — I'm not the only one."]`,
      why: "Amazon shoppers are already comparing products. This ad does the comparison for them and positions your product as the winner. \"Check the reviews\" sends them to your listing where reviews confirm the claim.",
      customization: "Don't name competitors directly — Amazon may reject the ad. Use category language: \"most serums\" instead of \"unlike Brand X.\"",
    },
  ],
  tips: [
    { title: "Design for muted autoplay", text: "Amazon video ads play muted in search results. Every key message must be communicated through text overlays. Sound is a bonus for the 20% who unmute." },
    { title: "Show the product in the first 2 seconds", text: "Amazon shoppers are scanning search results. If they can't identify your product in the video thumbnail, they'll scroll past. Product visibility in the first frame is critical." },
    { title: "Match the search intent", text: "Your video should answer the exact question the shopper searched for. If they searched \"best vitamin C serum for dark spots,\" your video should address dark spots specifically." },
    { title: "Design for the loop", text: "Amazon videos auto-loop. If your ending flows into your beginning, viewers watch multiple times — increasing engagement and click-through rate." },
    { title: "Target high-intent keywords", text: "Sponsored Brands Video works best on high-intent, product-specific keywords. Don't waste budget on broad category terms — target the keywords where shoppers are ready to buy." },
  ],
  dos: [
    "Use 16:9 landscape format — required for Sponsored Brands Video",
    "Add text overlays for every key message — videos play muted",
    "Show the product in the first 2 seconds — it's your thumbnail",
    "Match your video content to the search keyword intent",
    "Design the ending to loop seamlessly into the beginning",
    "Include a clear product shot in the final frames",
  ],
  donts: [
    "Don't rely on sound — Amazon videos autoplay muted",
    "Don't use vertical video — Amazon requires 16:9 landscape",
    "Don't name competitors directly — Amazon may reject the ad",
    "Don't hide the product — it should be visible throughout",
    "Don't use the same creative as social media — Amazon is a shopping context",
    "Don't exceed 30 seconds — shorter videos get higher completion rates in search results",
  ],
  ctaLine: "Create Amazon video ads that win the search results. No studio needed.",
};
export default data;
