import type { PlatformPageData } from "./_shared";

const data: PlatformPageData = {
  platform: "Email",
  h1: "AI Video for Email Marketing: Boost Open & Click Rates (2026)",
  verified: "March 2026",
  meta: "Add AI video to email marketing campaigns — technical specs, 3 email video scripts, embedding strategies, and the data on how video increases open and click rates.",
  intro: "Adding video to email increases click-through rates by 65% and reduces unsubscribes by 26%. But email and video have a complicated relationship: most email clients don't support embedded video playback. The workaround is using video thumbnails that link to a landing page or using animated GIF previews. When done right, video in email is the highest-ROI content format available — email already has a 36:1 ROI, and video amplifies it. This guide covers the technical specs, embedding strategies, and scripts for video email campaigns.",
  specs: [
    { label: "Thumbnail format", value: "Static image (JPG/PNG) or animated GIF linking to video" },
    { label: "Thumbnail size", value: "600×338px (16:9) or 600×600px (1:1) for email width" },
    { label: "Video hosting", value: "Host on landing page, YouTube, Vimeo, or Wistia — not in email" },
    { label: "Video aspect ratio", value: "16:9 (landscape) or 1:1 (square) for the landing page video" },
    { label: "Video duration", value: "30–90 seconds for email-linked video. Sweet spot: 45–60 seconds" },
    { label: "File format", value: ".mp4 on the landing page. GIF or static image in the email" },
    { label: "Play button overlay", value: "Add a visible play button to the thumbnail — increases clicks 20%+" },
    { label: "Alt text", value: "Required — describe the video for accessibility and image-blocked clients" },
    { label: "Fallback", value: "Always include a text link below the thumbnail for clients that block images" },
    { label: "Subject line", value: "Include [Video] or 🎥 in subject line — increases open rate 19%" },
  ],
  formats: [
    {
      name: "The Personal Video Email",
      why: "A video that feels like a personal message from a real person gets 4x more clicks than a generic product email. The thumbnail shows a face, which drives curiosity and clicks to the landing page.",
      structure: [
        { time: "0–5s", desc: "Greeting — personal, warm, reference the recipient's context" },
        { time: "5–20s", desc: "Value — share something useful, relevant, or exclusive" },
        { time: "20–40s", desc: "Offer or recommendation — connect the value to your product" },
        { time: "40–50s", desc: "CTA — clear next step with a link or button on the landing page" },
      ],
      length: "40–60 seconds",
      firstFrame: "Person looking at camera with a friendly expression. Play button overlay.",
    },
    {
      name: "The Product Announcement",
      why: "New product or feature announcements with video get 3x more engagement than text-only announcements. The video shows the product in action, which is more compelling than screenshots or descriptions.",
      structure: [
        { time: "0–3s", desc: "Hook — \"We just launched something you've been asking for...\"" },
        { time: "3–15s", desc: "Show the product/feature — quick demo or walkthrough" },
        { time: "15–25s", desc: "Key benefits — 2–3 specific improvements or use cases" },
        { time: "25–30s", desc: "CTA — \"Try it now\" or \"See it in action\"" },
      ],
      length: "25–35 seconds",
      firstFrame: "Product screenshot or person with the product. Play button overlay.",
    },
    {
      name: "The Testimonial Email",
      why: "Customer testimonial videos in email campaigns drive 2x higher conversion rates than text testimonials. Seeing and hearing a real person share their experience is more persuasive than reading a quote.",
      structure: [
        { time: "0–3s", desc: "Hook — \"Here's what [customer name/type] said about [product]...\"" },
        { time: "3–20s", desc: "Testimonial — the customer's story, problem, and result" },
        { time: "20–30s", desc: "Product connection — how the product delivered the result" },
        { time: "30–35s", desc: "CTA — \"Get the same results\" or \"Try it yourself\"" },
      ],
      length: "30–40 seconds",
      firstFrame: "Customer (or AI actor) speaking. Play button overlay. Quote text visible.",
    },
  ],
  scripts: [
    {
      name: "The Welcome Video Email",
      bestFor: "New subscriber onboarding, welcome sequences",
      duration: "40–50 seconds",
      script: `[GREETING — 0-5s]\n"Hey! Welcome to [brand]. I'm [name/role] and I\nwanted to personally welcome you."\n[Warm, direct to camera, genuine smile]\n\n[VALUE — 5-20s]\n"Here's what you can expect from us: [benefit 1],\n[benefit 2], and [benefit 3]. We're not going to\nspam you — every email has something useful."\n\n[QUICK WIN — 20-35s]\n"To get you started, here's a quick tip: [actionable\nadvice related to your product/service]. This alone\ncan [specific result]. Try it today."\n\n[CTA — 35-45s]\n"If you want to take it further, [product] does this\nautomatically. Check the link below this video.\nAnd reply to this email anytime — I read every one."\n[Friendly wave]`,
      why: "Welcome emails have the highest open rate of any email type (50–60%). Adding a personal video to the welcome email sets the tone for the entire relationship and drives 3x more clicks to your product.",
      customization: "The quick win tip must be genuinely useful without requiring a purchase. Give value first, pitch second. This builds trust that pays off in later emails.",
    },
    {
      name: "The Abandoned Cart Video",
      bestFor: "Cart recovery, high-value products",
      duration: "25–30 seconds",
      script: `[HOOK — 0-3s]\n"Hey — I noticed you were checking out [product]\nand didn't finish. Totally get it."\n[Casual, understanding tone — not pushy]\n\n[VALUE — 3-15s]\n"I wanted to share why people love this: [key benefit].\nOur customers say [specific testimonial point]. And\nright now [incentive if applicable — free shipping,\ndiscount, bonus]."\n\n[REASSURANCE — 15-22s]\n"If you're on the fence: [address common objection].\nWe have [guarantee/return policy] so there's zero risk."\n\n[CTA — 22-28s]\n"Your cart is saved — just click below to finish.\nOr reply if you have questions. Happy to help."`,
      why: "Abandoned cart emails recover 5–15% of lost sales. Adding video increases recovery rate by 20–30% because it addresses objections and adds social proof in a format that feels personal, not automated.",
      customization: "Address the #1 objection for your product. Price? \"Here's why it's worth it.\" Quality? \"Here's what real customers say.\" Shipping? \"It arrives in [timeframe].\"",
    },
    {
      name: "The Re-Engagement Video",
      bestFor: "Inactive subscribers, win-back campaigns",
      duration: "20–25 seconds",
      script: `[HOOK — 0-3s]\n"Hey — it's been a while! I wanted to check in\nand share what's new."\n[Friendly, not guilt-tripping]\n\n[UPDATE — 3-14s]\n"Since you've been away, we've [key update 1] and\n[key update 2]. Plus [new product/feature] that\nour customers are loving."\n\n[OFFER — 14-20s]\n"To welcome you back, [incentive — discount, free\ntrial, exclusive access]. It's our way of saying\nwe missed you."\n\n[CTA — 20-23s]\n"Click below to check it out. Good to have you back."`,
      why: "Re-engagement emails with video see 40% higher reactivation rates than text-only. The personal, friendly tone avoids the guilt-trip approach that turns people off.",
      customization: "The incentive should be genuine and exclusive to this re-engagement campaign. If they can get the same offer elsewhere, there's no urgency to re-engage.",
    },
  ],
  tips: [
    { title: "Use a thumbnail with a play button, not embedded video", text: "Most email clients (Gmail, Outlook, Yahoo) don't support embedded video. Use a static image or animated GIF with a play button overlay that links to your landing page. This works in 100% of email clients." },
    { title: "Add [Video] to your subject line", text: "Including the word \"Video\" or a 🎥 emoji in your subject line increases open rates by 19%. It sets expectations and creates curiosity." },
    { title: "Keep landing page videos under 60 seconds", text: "Email recipients who click through to watch a video have limited patience. 45–60 seconds is the sweet spot. Include a CTA button directly below the video on the landing page." },
    { title: "Always include a text fallback", text: "Some email clients block images by default. Include a text link below your video thumbnail: \"Can't see the video? Click here to watch.\" This captures clicks from image-blocked clients." },
    { title: "Test animated GIF vs static thumbnail", text: "Animated GIFs (3–5 seconds, under 1 MB) can increase clicks by 26% over static thumbnails. But they increase email size — test both and monitor deliverability." },
  ],
  dos: [
    "Use a video thumbnail with a play button overlay — not embedded video",
    "Add [Video] or 🎥 to subject lines for higher open rates",
    "Include a text link fallback for image-blocked email clients",
    "Keep landing page videos under 60 seconds",
    "Host videos on your landing page, not in the email itself",
    "Add alt text to the video thumbnail for accessibility",
  ],
  donts: [
    "Don't try to embed video directly in email — most clients won't play it",
    "Don't use GIFs over 1 MB — they slow email loading and hurt deliverability",
    "Don't send video emails without a text fallback link",
    "Don't make the landing page video longer than 90 seconds",
    "Don't forget the play button overlay — without it, recipients don't know it's a video",
    "Don't use autoplay on the landing page — let the visitor choose to play",
  ],
  ctaLine: "Create video content for email campaigns that boost clicks and conversions.",
};
export default data;
