import type { PlatformPageData } from "./_shared";

const data: PlatformPageData = {
  platform: "Instagram Stories",
  h1: "AI Video Ads for Instagram Stories: Specs & Templates (2026)",
  verified: "March 2026",
  meta: "Create high-converting AI video ads for Instagram Stories — exact specs, 3 ready-to-use scripts, format breakdowns, and the strategy that works in 2026.",
  intro: "Instagram Stories reach 500M+ daily users and have a tap-through rate that makes them one of the most effective ad placements on Meta. The catch: Stories ads compete with content from friends and family, so anything that looks like an ad gets swiped past instantly. UGC-style video ads in Stories see 1.6x higher completion rates than branded content because they match the format's native feel — vertical, casual, ephemeral. This guide covers specs, scripts, and strategy for Stories ads that convert.",
  specs: [
    { label: "Aspect ratio", value: "9:16 (full-screen vertical)" },
    { label: "Resolution", value: "1080×1920px recommended" },
    { label: "Video duration", value: "1–60 seconds per card. Sweet spot: 8–15 seconds" },
    { label: "Max file size", value: "4 GB" },
    { label: "File formats", value: ".mp4, .mov" },
    { label: "Safe zone (top)", value: "Keep text below top 14% (profile bar overlay)" },
    { label: "Safe zone (bottom)", value: "Avoid bottom 20% (swipe-up/CTA button area)" },
    { label: "Sound", value: "Optional — 60% of Stories are watched with sound on" },
    { label: "Captions", value: "Recommended — burned-in for silent viewers" },
    { label: "CTA button", value: "Auto-placed by Meta — \"Shop Now\", \"Learn More\", etc." },
  ],
  formats: [
    {
      name: "The Quick Confession",
      why: "Stories feel intimate — like a private message. Confession-style openings match this energy perfectly. The viewer feels like they're getting insider info, not watching an ad.",
      structure: [
        { time: "0–2s", desc: "Hook — whispered or conspiratorial tone: \"Okay I need to tell you something...\"" },
        { time: "2–6s", desc: "The confession — what you discovered, what changed" },
        { time: "6–10s", desc: "Quick proof — show the result or product" },
        { time: "10–12s", desc: "CTA — \"Swipe up before I change my mind\" or similar" },
      ],
      length: "10–15 seconds",
      firstFrame: "Close-up face, slightly leaning in, as if sharing a secret.",
    },
    {
      name: "The 3-Second Demo",
      why: "Stories are fast. Users tap through at 3–5 second intervals. This format front-loads the product demo into the first few seconds so even quick tappers see the product in action.",
      structure: [
        { time: "0–1s", desc: "Product in hand, movement starts immediately" },
        { time: "1–5s", desc: "Demo — show the product being used in real-time" },
        { time: "5–8s", desc: "Result — the clean surface, the glowing skin, the organized space" },
        { time: "8–10s", desc: "Text CTA overlay — \"Swipe up 👆\"" },
      ],
      length: "8–12 seconds",
      firstFrame: "Product in hand with movement. No static openings.",
    },
    {
      name: "The Poll/Question Opener",
      why: "Stories natively support interactive elements. Starting with a question mimics the poll/question sticker format, making the ad feel like interactive content rather than a promotion.",
      structure: [
        { time: "0–2s", desc: "Question on screen: \"Have you tried this yet?\" or \"Is your [product] doing this?\"" },
        { time: "2–7s", desc: "Answer the question with your product story" },
        { time: "7–10s", desc: "Show the result or product" },
        { time: "10–12s", desc: "CTA — \"Find out → Swipe up\"" },
      ],
      length: "10–15 seconds",
      firstFrame: "Bold text question on screen with face visible behind it.",
    },
  ],
  scripts: [
    {
      name: "The Secret Share",
      bestFor: "Any consumer product, cold audiences",
      duration: "12–15 seconds",
      script: `[HOOK — 0-2s]\n"Okay I don't usually share stuff like this but\nthis is too good to keep to myself..."\n[Close to camera, whispering slightly]\n\n[REVEAL — 2-8s]\n"I found this [product] and it literally [specific\nresult] in [timeframe]. I've been using it every\nday since."\n[Show product briefly]\n\n[CTA — 8-12s]\n"Swipe up — you'll thank me later."\n[Point up toward swipe area]`,
      why: "The conspiratorial tone matches Stories' intimate format. \"I don't usually share\" implies exclusivity. Short enough to hold attention through the full card.",
      customization: "Keep it under 15 seconds. Stories users are impatient — every second needs to earn its place.",
    },
    {
      name: "The Speed Result",
      bestFor: "Products with visible results, retargeting",
      duration: "8–12 seconds",
      script: `[HOOK — 0-1s]\n[TEXT ON SCREEN: "Watch this"]\n[Product in hand]\n\n[DEMO — 1-6s]\n[Apply/use product — quick, no pauses]\n[Voiceover: "One step. 30 seconds. Done."]\n\n[RESULT — 6-9s]\n[Show result]\n[TEXT ON SCREEN: "Every time 🤯"]\n\n[CTA — 9-11s]\n[TEXT ON SCREEN: "Swipe up 👆"]`,
      why: "Pure demo, no talking head. Works for products where the result is visual. The text-on-screen approach works well for Stories where many viewers have sound off.",
      customization: "The demo must be genuinely fast and impressive. If your product takes time to show results, use the testimonial format instead.",
    },
    {
      name: "The Before/After Flash",
      bestFor: "Skincare, cleaning, organization, fitness products",
      duration: "10–13 seconds",
      script: `[BEFORE — 0-3s]\n[TEXT ON SCREEN: "Before"]\n[Show the problem state clearly]\n\n[TRANSITION — 3-5s]\n[TEXT ON SCREEN: "2 weeks later..."]\n[Quick transition — snap cut or swipe]\n\n[AFTER — 5-9s]\n[TEXT ON SCREEN: "After"]\n[Show the result — same angle, same lighting]\n[Voiceover: "Same camera. No filter."]\n\n[CTA — 9-12s]\n[TEXT ON SCREEN: "Get yours → Swipe up"]\n[Voiceover: "Link above."]`,
      why: "Before/after is the most shareable format on Stories. \"Same camera, no filter\" adds credibility. The matching angles make the transformation undeniable.",
      customization: "The before and after must be shot from the same angle with similar lighting for maximum impact. Inconsistent framing kills credibility.",
    },
  ],
  tips: [
    { title: "Keep it under 15 seconds", text: "Stories ads that run 15 seconds or less see 2x higher completion rates than 30-second ads. Every second counts — if a frame doesn't add value, cut it." },
    { title: "Front-load everything", text: "The average Stories viewer decides to skip within 1.5 seconds. Your hook, your product, and your value proposition need to be visible immediately." },
    { title: "Design for sound-off first", text: "40% of Stories viewers have sound off. Use text overlays, burned-in captions, and visual storytelling that works without audio." },
    { title: "Use the swipe-up CTA naturally", text: "Meta auto-places a CTA button, but reinforce it verbally or with text: \"Swipe up\" with an arrow. Users need the prompt." },
    { title: "Test single-card vs multi-card", text: "Single 15-second cards often outperform 3-card sequences because there's no drop-off between cards. Start with single cards." },
  ],
  dos: [
    "Use 9:16 vertical — Stories are full-screen, anything else looks broken",
    "Add text overlays for key messages — many viewers watch without sound",
    "Start with movement or a face in the first frame",
    "Keep total duration under 15 seconds for best completion rates",
    "Use the native Stories aesthetic — casual, vertical, ephemeral-feeling",
    "Reinforce the swipe-up CTA with text and verbal cues",
  ],
  donts: [
    "Don't use horizontal video — it looks terrible in Stories",
    "Don't exceed 15 seconds unless you have a compelling reason",
    "Don't put important text in the top 14% or bottom 20% — UI elements cover them",
    "Don't start with a static frame — movement in the first second prevents skips",
    "Don't use the same creative for Stories and Feed — they're different formats",
    "Don't forget the CTA — Stories viewers won't swipe up unless prompted",
  ],
  ctaLine: "Create Stories ads that feel native. No camera, no creators, no editing.",
};
export default data;
