import type { PlatformPageData } from "./_shared";

const data: PlatformPageData = {
  platform: "LinkedIn",
  h1: "AI Video Ads for LinkedIn: B2B UGC That Converts (2026)",
  verified: "March 2026",
  meta: "Create AI video ads for LinkedIn — exact specs, 3 B2B-optimized scripts, format strategy, and what's actually driving results on LinkedIn video in 2026.",
  intro: "LinkedIn video ads get 3x more engagement than text posts and 5x more engagement than static image ads. But LinkedIn's audience is fundamentally different from consumer platforms: they're professionals evaluating solutions, not consumers browsing for entertainment. UGC-style video works on LinkedIn when it's adapted for B2B — think \"founder talking to camera about a real problem\" rather than \"influencer unboxing.\" The casual authenticity of UGC builds trust with B2B buyers who are tired of corporate marketing. This guide covers how to create LinkedIn video ads that convert professional audiences.",
  specs: [
    { label: "Aspect ratio", value: "1:1 (Feed, recommended), 9:16 (mobile), 16:9 (desktop)" },
    { label: "Resolution", value: "1080×1080 (1:1), 1920×1080 (16:9), 1080×1920 (9:16)" },
    { label: "Video duration", value: "3 seconds–30 minutes. Sweet spot: 15–45 seconds for ads" },
    { label: "Max file size", value: "200 MB" },
    { label: "File formats", value: ".mp4 (recommended)" },
    { label: "Sound", value: "Optional — many LinkedIn users browse at work without sound" },
    { label: "Captions", value: "Required — LinkedIn is a sound-off-first platform" },
    { label: "CTA button", value: "Customizable: Learn More, Sign Up, Download, Visit Website, etc." },
    { label: "Headline", value: "Max 70 characters recommended for full visibility" },
    { label: "Intro text", value: "Max 150 characters before \"see more\" truncation" },
  ],
  formats: [
    {
      name: "The Founder's Take",
      why: "LinkedIn audiences trust people, not brands. A founder or team member speaking directly to camera about a real industry problem feels authentic and builds credibility. This format consistently outperforms polished brand videos on LinkedIn.",
      structure: [
        { time: "0–3s", desc: "Hook — bold industry claim or contrarian take" },
        { time: "3–15s", desc: "Explain — why the status quo is broken, with specific examples" },
        { time: "15–30s", desc: "Solution — how your product/approach fixes it" },
        { time: "30–40s", desc: "CTA — \"Link in comments\" or \"DM me\" or CTA button" },
      ],
      length: "30–45 seconds",
      firstFrame: "Person at desk or in office setting. Professional but not corporate.",
    },
    {
      name: "The Customer Story",
      why: "B2B buyers trust peer recommendations more than vendor claims. A customer sharing their experience in a casual, unscripted-feeling format is the B2B equivalent of a consumer testimonial.",
      structure: [
        { time: "0–3s", desc: "Hook — \"We were spending [X hours/dollars] on [problem]...\"" },
        { time: "3–12s", desc: "Problem — describe the specific business challenge" },
        { time: "12–25s", desc: "Solution + result — what changed and the measurable outcome" },
        { time: "25–30s", desc: "CTA — \"Check the link\" or \"Happy to share more in DMs\"" },
      ],
      length: "25–35 seconds",
      firstFrame: "Professional person in a real work environment. Not a studio.",
    },
    {
      name: "The Quick Insight",
      why: "LinkedIn rewards thought leadership. A 15–20 second video sharing one actionable insight positions your brand as an authority and drives engagement through comments and shares.",
      structure: [
        { time: "0–2s", desc: "Hook — \"Here's what most [role] get wrong about [topic]...\"" },
        { time: "2–12s", desc: "Insight — one specific, actionable takeaway" },
        { time: "12–16s", desc: "Bridge — connect the insight to your product/service" },
        { time: "16–18s", desc: "CTA — \"Follow for more\" or \"Link in comments\"" },
      ],
      length: "15–20 seconds",
      firstFrame: "Person speaking with confidence. Text overlay with the topic.",
    },
  ],
  scripts: [
    {
      name: "The Industry Problem",
      bestFor: "SaaS, B2B services, professional tools",
      duration: "30–40 seconds",
      script: `[HOOK — 0-3s]\n"Every [industry] team I talk to has the same problem\nand nobody's talking about it."\n[Direct to camera, professional setting]\n\n[PROBLEM — 3-15s]\n"They're spending [X hours/week] on [manual process]\nthat should take [fraction of time]. The tools they're\nusing were built for [old paradigm] and they're forcing\nmodern workflows into outdated systems."\n\n[SOLUTION — 15-28s]\n"We built [product] specifically for this. [Key feature]\ncuts [process] from [old time] to [new time]. Our\ncustomers are saving [specific metric] per month.\nNot theoretical — measured."\n\n[CTA — 28-35s]\n"Link in the comments if you want to see how it works.\nOr DM me — happy to walk you through it."`,
      why: "\"Nobody's talking about it\" creates insider knowledge appeal. The specific time/money metrics make it credible. The DM offer feels personal and LinkedIn-native.",
      customization: "Replace the problem, metrics, and solution with your specifics. The key is specificity — B2B buyers see through vague claims instantly.",
    },
    {
      name: "The Customer Win",
      bestFor: "B2B products with measurable ROI",
      duration: "25–30 seconds",
      script: `[HOOK — 0-3s]\n"One of our customers just shared their 90-day results\nand I had to post this."\n[Genuine excitement, professional setting]\n\n[STORY — 3-18s]\n"They were [old situation — specific pain point].\nAfter switching to [product], they [specific result]\nin [timeframe]. Their [key metric] went from [before]\nto [after]. That's a [percentage] improvement."\n\n[BRIDGE — 18-24s]\n"This isn't an outlier. We're seeing similar results\nacross [number] customers in [industry]."\n\n[CTA — 24-28s]\n"Link in comments to see the full case study.\nOr comment 'results' and I'll send it to you."`,
      why: "Third-party results are more credible than self-promotion on LinkedIn. The \"comment 'results'\" CTA drives engagement, which boosts the post's visibility in the algorithm.",
      customization: "Use real metrics. B2B audiences on LinkedIn will verify claims. Round numbers feel made up — \"43% improvement\" is more credible than \"50% improvement.\"",
    },
    {
      name: "The Quick Tip",
      bestFor: "Thought leadership, top-of-funnel awareness",
      duration: "16–20 seconds",
      script: `[HOOK — 0-2s]\n"Quick tip for [role/industry] teams:"\n[Direct to camera, confident]\n\n[TIP — 2-12s]\n"Stop [common mistake]. Instead, [better approach].\nThe difference: [specific outcome]. We see this\nwith every team we work with."\n\n[BRIDGE — 12-16s]\n"This is exactly what [product] automates. But even\nif you do it manually, stop [mistake] today."\n\n[CTA — 16-19s]\n"Follow for more [industry] tips. Link in comments\nif you want the full breakdown."`,
      why: "Giving genuine value without requiring a purchase builds trust. The \"even if you do it manually\" line shows you care about helping, not just selling. LinkedIn audiences reward this with engagement.",
      customization: "The tip must be genuinely useful. If someone can implement it without your product, that's good — it builds trust that makes them more likely to buy later.",
    },
  ],
  tips: [
    { title: "Captions are mandatory, not optional", text: "80%+ of LinkedIn video is watched without sound. If your message isn't readable through captions and text overlays, you're invisible to most of your audience." },
    { title: "Use 1:1 for Feed, 9:16 for mobile-first", text: "Square (1:1) video takes up the most space in LinkedIn's desktop feed. If your audience is primarily mobile, test 9:16 vertical. Provide both if possible." },
    { title: "Post the link in comments, not the post", text: "LinkedIn's algorithm deprioritizes posts with external links. Put your CTA link in the first comment instead of the post body for 2–3x more reach." },
    { title: "Longer is okay on LinkedIn", text: "Unlike TikTok and Snapchat, LinkedIn audiences will watch 30–60 second videos if the content is valuable. Don't cut valuable content just to hit a short duration." },
    { title: "Engage with comments in the first hour", text: "LinkedIn's algorithm heavily weights early engagement. Reply to every comment in the first 60 minutes to boost distribution." },
  ],
  dos: [
    "Add burned-in captions — LinkedIn is a sound-off platform",
    "Use 1:1 aspect ratio for maximum Feed visibility",
    "Put links in comments, not in the post body",
    "Use professional but casual tone — not corporate, not too informal",
    "Include specific metrics and results — B2B audiences demand proof",
    "Engage with comments quickly to boost algorithmic distribution",
  ],
  donts: [
    "Don't use consumer UGC style (selfie, bedroom, casual slang) — adapt for professional context",
    "Don't put external links in the post body — it kills reach",
    "Don't use vague claims (\"game-changing\", \"revolutionary\") — B2B audiences tune them out",
    "Don't make videos shorter than 15 seconds — LinkedIn rewards depth",
    "Don't ignore captions — most LinkedIn viewing is silent",
    "Don't use the same creative as your TikTok or Instagram campaigns — different audience, different tone",
  ],
  ctaLine: "Create LinkedIn video ads that build trust with B2B buyers. No studio needed.",
};
export default data;
