import type { PlatformPageData } from "./_shared";

const data: PlatformPageData = {
  platform: "Snapchat",
  h1: "AI UGC Video Ads for Snapchat: Specs & Best Practices (2026)",
  verified: "March 2026",
  meta: "Create AI UGC video ads for Snapchat — exact specs, 3 proven scripts, format breakdowns, and the creative strategy that converts on Snapchat in 2026.",
  intro: "Snapchat reaches 75% of 13–34 year olds in 25+ countries. The platform's ad environment is unique: ads appear between Stories and in the Discover feed, competing with content from friends. If your ad doesn't feel native to Snapchat's casual, ephemeral aesthetic, it gets swiped past in under a second. UGC-style video ads on Snapchat see 2x higher swipe-up rates than polished brand content. This guide covers the specs, formats, and scripts that work on Snapchat in 2026.",
  specs: [
    { label: "Aspect ratio", value: "9:16 (full-screen vertical, required)" },
    { label: "Resolution", value: "1080×1920px recommended" },
    { label: "Video duration", value: "3–180 seconds. Sweet spot: 5–10 seconds" },
    { label: "Max file size", value: "1 GB" },
    { label: "File formats", value: ".mp4, .mov (H.264 encoded)" },
    { label: "Safe zone (top)", value: "Avoid top 150px (brand name and headline)" },
    { label: "Safe zone (bottom)", value: "Avoid bottom 300px (CTA button area)" },
    { label: "Sound", value: "Recommended — 64% of Snapchat ads are viewed with sound" },
    { label: "Captions", value: "Recommended — burned-in for silent viewers" },
    { label: "Attachment", value: "Website, app install, or long-form video" },
  ],
  formats: [
    {
      name: "The Snap-Native Testimonial",
      why: "Snapchat's aesthetic is raw and unfiltered. Testimonials that look like they were filmed on a phone in someone's bedroom perform best because they match the platform's native content style.",
      structure: [
        { time: "0–1s", desc: "Hook — immediate, no intro. \"You NEED to know about this...\"" },
        { time: "1–4s", desc: "Quick story — problem + discovery in 3 seconds" },
        { time: "4–7s", desc: "Result — show or describe the outcome" },
        { time: "7–9s", desc: "CTA — \"Swipe up\" with urgency" },
      ],
      length: "7–10 seconds",
      firstFrame: "Close-up face, phone-quality feel, no branding visible.",
    },
    {
      name: "The Snap Story Ad",
      why: "Story ads appear between friends' Stories. The format needs to feel like a friend's Story — casual, quick, personal. Any hint of production value breaks the illusion.",
      structure: [
        { time: "0–2s", desc: "Casual opening — \"Okay so...\" or \"Wait wait wait...\"" },
        { time: "2–5s", desc: "Show the product or result — quick, handheld feel" },
        { time: "5–8s", desc: "One key benefit — specific, not generic" },
        { time: "8–10s", desc: "CTA — \"Swipe up, trust me\"" },
      ],
      length: "8–12 seconds",
      firstFrame: "Selfie-style, slightly off-center, natural lighting. Looks like a real Snap.",
    },
    {
      name: "The Quick Demo Snap",
      why: "Snapchat users have the shortest attention span of any platform. A 5–7 second demo that shows the product in action with no preamble captures attention before the swipe reflex kicks in.",
      structure: [
        { time: "0–1s", desc: "Product in frame, movement starts immediately" },
        { time: "1–4s", desc: "Demo — show it working in real-time" },
        { time: "4–6s", desc: "Result — the payoff" },
        { time: "6–7s", desc: "Text CTA — \"Swipe up 👆\"" },
      ],
      length: "5–8 seconds",
      firstFrame: "Product in motion. Zero static frames.",
    },
  ],
  scripts: [
    {
      name: "The Quick Testimonial",
      bestFor: "Any consumer product, Gen Z and young millennial audiences",
      duration: "8–10 seconds",
      script: `[HOOK — 0-1s]\n"Okay I'm obsessed with this thing"\n[Selfie-style, casual, energetic]\n\n[SHOW — 1-5s]\n"I got it [timeframe] ago and [specific result].\nLike, look — [show result or product]."\n\n[CTA — 5-8s]\n"Swipe up before it sells out. I'm not kidding."\n[Point up]`,
      why: "Short, energetic, and casual. Matches how Snapchat users actually talk to their friends. The urgency CTA (\"before it sells out\") drives immediate action.",
      customization: "Keep the energy high and the language casual. Snapchat's audience is young — formal language feels out of place. Use slang naturally.",
    },
    {
      name: "The Story-Style Share",
      bestFor: "Products with a discovery story, cold audiences",
      duration: "10–12 seconds",
      script: `[HOOK — 0-2s]\n"Wait — have you guys seen this yet?"\n[Excited, leaning into camera]\n\n[SHARE — 2-7s]\n"My [friend/sister/coworker] put me on to this and\nI literally can't stop using it. It [key benefit]\nand it's only [price]."\n\n[CTA — 7-10s]\n"Swipe up. You're gonna thank me.\nI'm telling everyone about this."`,
      why: "The \"have you seen this\" hook mimics how people actually share discoveries on Snapchat. The third-party recommendation (\"my friend put me on to this\") adds social proof.",
      customization: "The referral source should match your audience. \"My sister\" for beauty. \"My trainer\" for fitness. \"My coworker\" for productivity tools.",
    },
    {
      name: "The 5-Second Demo",
      bestFor: "Products with visible results, impulse purchases",
      duration: "5–7 seconds",
      script: `[0-1s]\n[Product in hand, start using immediately]\n\n[1-4s]\n[Quick demo — show it working]\n[TEXT ON SCREEN: "[Key benefit] in [timeframe]"]\n\n[4-6s]\n[Show result]\n[TEXT ON SCREEN: "Swipe up 👆"]\n[Voiceover: "You need this."]`,
      why: "5 seconds. No intro, no story, just product in action. For Snapchat's attention span, sometimes the shortest ad wins.",
      customization: "The demo must be visually compelling enough to stop a swipe in under 1 second. If your product doesn't have a visual wow factor, use the testimonial format instead.",
    },
  ],
  tips: [
    { title: "Keep it under 10 seconds", text: "Snapchat's optimal ad length is 5–10 seconds. Completion rates drop 50% after 10 seconds. Say less, show more, and get to the CTA fast." },
    { title: "Match the Snapchat aesthetic", text: "Snapchat content is raw, vertical, and personal. Ads that look too polished get swiped past. Use selfie-style framing, natural lighting, and casual language." },
    { title: "Use Snap Pixel for optimization", text: "Install the Snap Pixel on your site and optimize for purchase events, not swipe-ups. The algorithm will find buyers, not just clickers." },
    { title: "Target by interest, not just demographics", text: "Snapchat's interest-based targeting is underrated. Layer interests (\"skincare enthusiasts\" + \"online shoppers\") for better performance than broad age/gender targeting." },
    { title: "Test Snap Ads vs Story Ads separately", text: "Snap Ads (between content) and Story Ads (in Discover) have different contexts. Create separate creatives for each placement and test independently." },
  ],
  dos: [
    "Use 9:16 vertical format — no exceptions on Snapchat",
    "Keep ads under 10 seconds for best completion rates",
    "Use selfie-style framing and casual language",
    "Add burned-in captions for silent viewers",
    "Include a clear swipe-up CTA in the last 2 seconds",
    "Match the raw, unfiltered Snapchat aesthetic",
  ],
  donts: [
    "Don't use polished, studio-quality production — it screams \"ad\" on Snapchat",
    "Don't exceed 10 seconds unless you have exceptional content",
    "Don't use formal or corporate language — Snapchat's audience is young and casual",
    "Don't put important content in the top 150px or bottom 300px — UI overlays cover them",
    "Don't reuse Instagram or TikTok creative without adapting — Snapchat has its own aesthetic",
    "Don't ignore the swipe-up CTA — Snapchat users need explicit direction",
  ],
  ctaLine: "Create Snapchat video ads that feel native. No camera, no creators, no editing.",
};
export default data;
