import type { PlatformPageData } from "./_shared";

const data: PlatformPageData = {
  platform: "TikTok",
  h1: "AI UGC Video Ads for TikTok: Specs, Scripts & Strategy",
  verified: "March 2026",
  meta: "Everything you need to create AI UGC video ads for TikTok in 2026 — exact specs, 3 ready-to-use scripts, creative testing framework, and what's actually working right now.",
  intro: "TikTok's algorithm rewards content that looks native. Polished, branded video ads get punished — lower completion rates, higher CPMs, worse delivery. UGC-style content consistently outperforms: 2.3x higher completion rates and 1.7x better click-through rates compared to studio-produced ads. That's not a trend — it's how the algorithm works. This page covers the exact specs, the formats that work, 3 scripts you can use today, and the creative testing framework that separates brands scaling on TikTok from brands burning money.",
  specs: [
    { label: "Aspect ratio", value: "9:16 (recommended), 1:1, 16:9 supported" },
    { label: "Resolution", value: "Min 540×960px. Recommended: 1080×1920px" },
    { label: "Video duration", value: "5–60 seconds. Sweet spot: 15–30 seconds" },
    { label: "Max file size", value: "500 MB" },
    { label: "File formats", value: ".mp4, .mov, .mpeg, .avi" },
    { label: "Safe zone (text)", value: "Keep text within 44px from top, 140px from bottom" },
    { label: "Safe zone (profile)", value: "Keep key visuals away from right 20%" },
    { label: "Sound", value: "Required — 93% of top-performing ads use audio" },
    { label: "Captions", value: "Recommended — burned-in for accessibility" },
    { label: "Bitrate", value: "Recommended: 2,500 kbps+" },
  ],
  formats: [
    {
      name: "The Native Testimonial",
      why: "TikTok's algorithm treats this format almost like organic content because it mirrors how real creators post. Selfie-style framing, natural lighting, casual speech. The algorithm can't easily distinguish it from a regular TikTok.",
      structure: [
        { time: "0–2s", desc: "Hook — emotional or surprising opening line, directly to camera" },
        { time: "2–8s", desc: "Story — the problem, the discovery, the experience (conversational)" },
        { time: "8–15s", desc: "Result — what changed, how it feels now" },
        { time: "15–18s", desc: "CTA — casual, not salesy (\"link in bio, trust me\")" },
      ],
      length: "15–21 seconds",
      firstFrame: "Close-up of face, natural lighting, no branding visible. Should look like a FYP video, not an ad.",
    },
    {
      name: "The Stitch-Style Reaction",
      why: "Mimics TikTok's native \"Stitch\" feature — looks like someone reacting to another video. Triggers curiosity because the viewer feels like they're watching a conversation, not an ad. High thumb-stop rate.",
      structure: [
        { time: "0–2s", desc: "\"I saw this [product/claim/trend] and had to try it...\"" },
        { time: "2–6s", desc: "Show the product or reference what they're reacting to" },
        { time: "6–15s", desc: "Honest reaction/experience — skepticism turned to belief" },
        { time: "15–18s", desc: "CTA — \"okay I'm convinced, link in bio\"" },
      ],
      length: "15–20 seconds",
      firstFrame: "Person looking at phone or off-camera (as if watching another video).",
    },
    {
      name: "The Rapid-Fire Demo",
      why: "TikTok rewards fast pacing. Quick cuts, text overlays, punchy voiceover. No slow intros. Works especially well for products with a visible result (skincare, cleaning, food).",
      structure: [
        { time: "0–1s", desc: "Bold text hook on screen + voiceover: \"Watch this\"" },
        { time: "1–8s", desc: "Product demo with 3–4 quick cuts showing different angles/uses" },
        { time: "8–12s", desc: "Result shot — the clean surface, the glowing skin" },
        { time: "12–15s", desc: "CTA text overlay + voiceover" },
      ],
      length: "12–15 seconds",
      firstFrame: "Product in hand or bold text on screen. Movement in the first frame is critical.",
    },
  ],
  scripts: [
    {
      name: "The Honest Testimonial",
      bestFor: "Any consumer product, cold and warm audiences",
      duration: "18–22 seconds",
      script: `[HOOK — 0-2s]\n"Okay I need to be honest about something..."\n[Look directly at camera, slightly hesitant expression]\n\n[STORY — 2-10s]\n"I bought this because TikTok made me do it and I was\nfully expecting to return it. But it's been 2 weeks and\nI literally can't stop using it."\n[Hold product casually, gesture naturally]\n\n[RESULT — 10-16s]\n"Look at this. [Show result — skin, clean surface, etc.]\nI've tried so many things and this is the first one that\nactually did what it said it would."\n\n[CTA — 16-20s]\n"I'm not even joking, go get this. Link in bio."\n[Point down toward bio link area]`,
      why: "The \"I need to be honest\" hook creates tension. The \"TikTok made me do it\" reference makes it feel native. The casual language matches how real TikTok creators talk.",
      customization: "Replace the product reference and result with yours. Keep the hesitant-to-convinced emotional arc — it's the structure that converts.",
    },
    {
      name: "The Controversy Hook",
      bestFor: "Products that challenge conventional wisdom, health/beauty/cleaning",
      duration: "15–18 seconds",
      script: `[HOOK — 0-2s]\n"Your [product category] is probably making things worse.\nHere's why."\n[Serious expression, direct to camera]\n\n[EXPLAIN — 2-8s]\n"Most [product category] products use [common ingredient]\nwhich actually [negative effect]. I switched to [product]\nbecause it uses [better ingredient] instead."\n\n[PROOF — 8-13s]\n"After [timeframe], [specific result]. Not even kidding."\n[Show product or result]\n\n[CTA — 13-16s]\n"Check yours. Then check this one. Link in bio."\n[Hold up product]`,
      why: "Controversy hooks have the highest thumb-stop rate on TikTok — they trigger \"wait, am I doing something wrong?\" which is impossible to scroll past.",
      customization: "The controversy must be real and defensible. The \"check yours, then check this one\" CTA creates a comparison moment.",
    },
    {
      name: "The Speed Demo",
      bestFor: "Products with visible results, e-commerce, cold audiences",
      duration: "12–15 seconds",
      script: `[HOOK — 0-1s]\n[TEXT ON SCREEN: "Watch this"]\n[Product in hand, movement starts immediately]\n\n[DEMO — 1-8s]\n[Quick cuts showing product in use]\n[Voiceover: "One pump. Spread it on. Wait 30 seconds."]\n[Each step = 2 seconds max, keep cutting]\n\n[RESULT — 8-11s]\n[Show the result — clean, glowing, transformed]\n[Voiceover: "Every. Single. Time."]\n\n[CTA — 11-14s]\n[TEXT ON SCREEN: "Link in bio 👇"]\n[Voiceover: "You need this."]`,
      why: "No talking head, no long intro — just product in action. Short demos get watched to the end and rewatched. The text-on-screen hook matches native TikTok content.",
      customization: "The specific demo steps depend on your product. The key is speed: never spend more than 2 seconds on any single shot.",
    },
  ],
  tips: [
    { title: "Test hooks independently, not whole videos", text: "Write one solid body + CTA, then create 5 versions with different hooks. TikTok's algorithm decides in the first 0.5–1 second. Test hooks first, optimize everything else second." },
    { title: "Spend $30–$50 per variation before judging", text: "TikTok needs data to optimize. Killing an ad after $10 doesn't give the algorithm enough signal. Run each variation for at least $30 — that's 3,000–10,000 impressions." },
    { title: "Use Spark Ads for your winners", text: "Once you find a creative that works, run it as a Spark Ad. They get 30–40% higher engagement because they look like organic posts with social proof." },
    { title: "Refresh creatives every 7–14 days", text: "TikTok creative fatigue hits faster than any other platform. Always have 3–5 new creatives in the pipeline. This is where AI batch generation pays for itself." },
    { title: "Test vertical (9:16) only", text: "Square and horizontal technically work but waste screen real estate and signal \"this wasn't made for TikTok.\" Always create in 9:16. No exceptions." },
  ],
  dos: [
    "Use trending sounds (even at low volume under voiceover) — signals native content",
    "Start with movement in the first frame — static openings get scrolled past",
    "Add burned-in captions — increase watch time by 15–25%",
    "Film (or generate) in selfie-style framing — matches how creators post",
    "Use TikTok's native fonts for text overlays when possible",
    "Keep the first 2 seconds surprising, emotional, or visually striking",
  ],
  donts: [
    "Don't put your logo in the first 3 seconds — it screams \"ad\"",
    "Don't use horizontal video cropped to vertical — black bars = instant skip",
    "Don't use corporate language (\"We're excited to announce...\")",
    "Don't start with the product name — start with a hook",
    "Don't use the same creative for more than 2 weeks",
    "Don't use stock music — use trending sounds or original audio",
  ],
  ctaLine: "Create TikTok video ads in minutes. No camera, no creators, no editing.",
};
export default data;
