import type { PlatformPageData } from "./_shared";

const data: PlatformPageData = {
  platform: "YouTube Shorts",
  h1: "AI UGC Videos for YouTube Shorts: Scripts & Strategy (2026)",
  verified: "March 2026",
  meta: "Create AI UGC video ads for YouTube Shorts — exact specs, 3 proven scripts, format strategy, and what's driving results on Shorts in 2026.",
  intro: "YouTube Shorts gets 70B+ daily views and is YouTube's fastest-growing format. For advertisers, Shorts offers something TikTok and Reels don't: intent-rich audiences. YouTube users are already in discovery mode — searching, watching, learning. When your UGC-style Shorts ad appears between organic content, it catches viewers in a high-attention state. Brands running UGC-style Shorts ads report 20–35% lower CPAs compared to traditional YouTube pre-roll. This guide covers specs, formats, scripts, and the strategy that works.",
  specs: [
    { label: "Aspect ratio", value: "9:16 (vertical, required)" },
    { label: "Resolution", value: "1080×1920px recommended" },
    { label: "Video duration", value: "15–60 seconds. Sweet spot: 15–30 seconds" },
    { label: "Max file size", value: "256 MB for Shorts uploads" },
    { label: "File formats", value: ".mp4, .mov, .webm" },
    { label: "Safe zone", value: "Avoid bottom 15% (subscribe button, title) and right 10% (like/dislike)" },
    { label: "Sound", value: "Required — YouTube Shorts autoplay with sound on" },
    { label: "Captions", value: "Recommended — increases accessibility and watch time" },
    { label: "Loop behavior", value: "Shorts auto-loop — design your ending to flow into the beginning" },
    { label: "Title", value: "Max 100 characters. Include primary keyword for search discovery" },
  ],
  formats: [
    {
      name: "The Educational Hook",
      why: "YouTube audiences are in learning mode. Educational content that teaches something in 30 seconds gets high retention and shares. Position your product as the tool that enables the lesson.",
      structure: [
        { time: "0–2s", desc: "Hook — \"Here's something most people get wrong about [topic]...\"" },
        { time: "2–12s", desc: "Teach — share a genuine insight, tip, or correction" },
        { time: "12–20s", desc: "Bridge — connect the lesson to your product naturally" },
        { time: "20–25s", desc: "CTA — \"Link in description\" or \"Check the pinned comment\"" },
      ],
      length: "20–30 seconds",
      firstFrame: "Person speaking directly to camera with text overlay of the topic.",
    },
    {
      name: "The Transformation Story",
      why: "YouTube loves narrative. A quick before/during/after story arc in 20 seconds gives viewers the satisfaction of a complete story — and positions your product as the turning point.",
      structure: [
        { time: "0–2s", desc: "Before — \"[Timeframe] ago, I was dealing with [problem]...\"" },
        { time: "2–8s", desc: "During — \"Then I started using [product/method]\"" },
        { time: "8–15s", desc: "After — show or describe the result with specifics" },
        { time: "15–18s", desc: "CTA — \"Link in description if you want to try it\"" },
      ],
      length: "15–20 seconds",
      firstFrame: "Person with a relatable expression — frustrated, tired, or curious.",
    },
    {
      name: "The Myth Buster",
      why: "Contrarian content performs exceptionally well on YouTube Shorts because it triggers the \"wait, really?\" response. Debunking a common belief and presenting your product as the correct approach drives high engagement.",
      structure: [
        { time: "0–2s", desc: "Myth — \"Everyone says you should [common advice]. They're wrong.\"" },
        { time: "2–10s", desc: "Why it's wrong — explain briefly with authority" },
        { time: "10–18s", desc: "What to do instead — introduce your product/approach" },
        { time: "18–22s", desc: "CTA — \"Try this instead. Link in description.\"" },
      ],
      length: "18–25 seconds",
      firstFrame: "Confident expression, text overlay with the myth statement.",
    },
  ],
  scripts: [
    {
      name: "The Quick Lesson",
      bestFor: "SaaS, education, health, beauty — any product with a teachable angle",
      duration: "22–28 seconds",
      script: `[HOOK — 0-3s]\n"Most people waste money on [category] because they\ndon't know this one thing..."\n[Direct to camera, authoritative but casual]\n\n[TEACH — 3-15s]\n"[Common approach] doesn't work because [reason].\nWhat actually works is [insight]. The difference is\n[specific detail that proves expertise]."\n\n[BRIDGE — 15-22s]\n"That's exactly why I switched to [product]. It's\nbuilt around [the correct approach] instead of\n[the common mistake]. And the results speak for\nthemselves — [specific result]."\n\n[CTA — 22-26s]\n"Link in the description if you want to try it.\nStop wasting money on [wrong approach]."`,
      why: "Educational hooks have the highest save rate on YouTube Shorts. Viewers save content they want to reference later — and saves signal the algorithm to push the video to more people.",
      customization: "The lesson must be genuinely useful, not just a setup for a pitch. If the viewer learns something real, they'll trust the product recommendation.",
    },
    {
      name: "The 30-Day Result",
      bestFor: "Products with measurable results over time",
      duration: "18–22 seconds",
      script: `[HOOK — 0-2s]\n"30 days ago I started [using product/doing method]\nand here's what happened..."\n[Direct to camera, genuine expression]\n\n[JOURNEY — 2-12s]\n"Week 1: [early observation — honest, not oversold]\nWeek 2: [first real change noticed]\nWeek 3: [momentum building]\nWeek 4: [the result that convinced me]"\n\n[RESULT — 12-17s]\n"[Show or describe the final result with specifics].\nI'm not going back to [old way]."\n\n[CTA — 17-20s]\n"Link in description. Give it 30 days — you'll see."`,
      why: "The week-by-week structure creates a mini-narrative that's easy to follow. It also sets realistic expectations, which builds trust.",
      customization: "Be honest about the timeline. If results take 60 days, say 60 days. Overpromising kills credibility on YouTube where audiences are more skeptical.",
    },
    {
      name: "The Myth Breaker",
      bestFor: "Products that challenge conventional wisdom",
      duration: "20–25 seconds",
      script: `[HOOK — 0-2s]\n"Stop doing [common practice]. It's actually making\n[problem] worse."\n[Serious expression, direct to camera]\n\n[EXPLAIN — 2-12s]\n"Here's why: [common practice] causes [negative effect]\nbecause [scientific or logical reason]. Most brands\nwon't tell you this because [reason]."\n\n[SOLUTION — 12-18s]\n"What works instead: [your approach]. [Product] does\nthis by [mechanism]. After [timeframe], [result]."\n\n[CTA — 18-22s]\n"Check the description. And stop [common practice] —\nyour [problem area] will thank you."`,
      why: "Contrarian content gets 3x more comments on YouTube Shorts because people want to debate. Comments boost the algorithm signal, which drives more views.",
      customization: "The myth must be genuinely debatable and your counter-argument must be defensible. Don't make claims you can't back up — YouTube audiences will call you out.",
    },
  ],
  tips: [
    { title: "Optimize for the loop", text: "Shorts auto-loop. If your ending flows naturally into your beginning, viewers watch multiple times without realizing it. Multiple views = higher retention signal = more distribution." },
    { title: "Use the description for SEO", text: "YouTube Shorts are searchable. Include your target keyword in the title and description. This gives your Shorts ad long-tail organic traffic beyond the paid campaign." },
    { title: "Sound is non-negotiable", text: "Unlike Instagram and Facebook, YouTube Shorts autoplay with sound on. Your audio quality matters — clear voiceover, no background noise, good pacing." },
    { title: "Test educational vs emotional hooks", text: "YouTube audiences respond to both, but educational hooks tend to get higher save rates while emotional hooks get higher share rates. Test both and optimize for your goal." },
    { title: "Pin a comment with your link", text: "In addition to the description link, pin a comment with your CTA and link. Pinned comments get 3–5x more clicks than description links on Shorts." },
  ],
  dos: [
    "Use 9:16 vertical format — required for Shorts",
    "Include sound — Shorts autoplay with audio on",
    "Add a keyword-rich title for search discovery",
    "Design the ending to loop seamlessly into the beginning",
    "Pin a comment with your link and CTA",
    "Keep it under 30 seconds for ads — completion rate drops after 30s",
  ],
  donts: [
    "Don't repurpose horizontal YouTube videos as Shorts — create native vertical content",
    "Don't ignore the description — it's indexed for search",
    "Don't use silent or music-only Shorts for ads — voiceover converts better",
    "Don't exceed 60 seconds — Shorts has a hard cap",
    "Don't use clickbait hooks you can't deliver on — YouTube audiences are skeptical",
    "Don't forget to add captions even though sound is on — accessibility matters",
  ],
  ctaLine: "Create YouTube Shorts ads that educate and convert. No camera needed.",
};
export default data;
