import type { GlossaryPageData } from "./_shared";
const data: GlossaryPageData = {
  term: "AI Subtitling",
  h1: "What Is AI Subtitling? Auto-Generate Captions",
  meta: "AI subtitling automatically generates captions and subtitles for video content. Learn why captions are essential for social media ads and how AI makes subtitling fast and affordable.",
  definition: "AI subtitling is the automated generation of text captions for video content using speech recognition and natural language processing. The AI listens to the audio track, transcribes the speech, and overlays timed text on the video. For advertising, AI subtitles ensure your message is communicated even when viewers watch without sound — which is how 85% of social media video is consumed.",
  whyMatters: [
    { label: "85% of social video is watched on mute", text: "Most people scroll social media in public, at work, or in bed next to a sleeping partner — all situations where sound is off. Without captions, 85% of your audience misses your entire message. Adding captions to video ads increases average view time by 12% and improves conversion rates by 15–25%. Captions aren't optional — they're essential." },
    { label: "They improve accessibility", text: "Captions make your content accessible to deaf and hard-of-hearing viewers — approximately 15% of the global population. Beyond being the right thing to do, accessibility compliance is increasingly required by advertising platforms and regulations. Captioned content also performs better with non-native speakers who can read the language more easily than they can understand spoken audio." },
    { label: "They reinforce your message", text: "When viewers both hear and read your message simultaneously, retention increases by 40%. Captions act as a second channel of communication, reinforcing key points and ensuring important details (product names, prices, URLs) are clearly communicated even if the audio is unclear or the viewer is distracted." },
  ],
  howItWorks: [
    { heading: "AI Subtitle Generation", text: "Modern AI subtitling works in three steps: speech recognition (the AI transcribes the audio into text with 95–99% accuracy), timing alignment (each word or phrase is synced to the exact moment it's spoken), and styling (the text is formatted with font, size, color, and positioning appropriate for the platform). Advanced tools also offer: auto-translation (generating subtitles in languages different from the audio), keyword highlighting (emphasizing key words with color or animation), and smart line breaks (ensuring readable text segments)." },
    { heading: "Caption Styles for Ads", text: "The most effective caption styles for social media ads are: word-by-word highlight (each word lights up as it's spoken — creates a karaoke effect that keeps eyes on the text), centered bold text (large, high-contrast text in the center of the frame — maximum readability), and animated text (words that pop, slide, or scale — adds visual energy). The style should match your brand and platform: TikTok favors animated, energetic captions while LinkedIn favors clean, professional subtitles." },
  ],
  example: "A DTC brand runs the same video ad with and without captions on Meta. Without captions: 22% thumb-stop rate, 0.9% CTR, $34 CPA. With animated word-by-word captions: 31% thumb-stop rate, 1.4% CTR, $22 CPA. The captions improve every metric because they serve double duty: they communicate the message to muted viewers AND they add visual movement that catches the eye during scrolling. The brand makes captions mandatory for all future video ads.",
  product: {
    intro: "members.mom includes caption support to ensure your videos perform with sound on or off:",
    points: [
      "Caption-ready output — Videos generated by members.mom are designed with caption placement in mind. The framing leaves space for text overlays without obscuring the presenter's face or key visual elements.",
      "Script-based accuracy — Because members.mom generates video from your script, caption text is 100% accurate — no speech recognition errors, no misheard words, no manual correction needed.",
      "Optimized for muted viewing — Every video is designed to communicate effectively even on mute, with visual cues and text elements that convey your message without relying on audio. Plans from $49/mo.",
    ],
  },
  related: [
    { term: "AI Dubbing", slug: "ai-dubbing" },
    { term: "Video Localization", slug: "video-localization" },
    { term: "Text-to-Speech (TTS)", slug: "text-to-speech" },
    { term: "Short-Form Video", slug: "short-form-video" },
    { term: "Vertical Video", slug: "vertical-video" },
    { term: "Scroll-Stopping Content", slug: "scroll-stopping" },
  ],
  relatedNote: "AI subtitling complements AI dubbing — subtitles provide text accessibility while dubbing provides audio localization. Both support video localization for global markets. Captions are especially critical for short-form video and vertical video on mobile, where muted viewing is the norm. Well-styled captions also contribute to scroll-stopping effectiveness.",
};
export default data;
