import type { GlossaryPageData } from "./_shared";
const data: GlossaryPageData = {
  term: "Content Repurposing",
  h1: "What Is Content Repurposing? One Asset, Many Formats",
  meta: "Content repurposing adapts a single piece of content into multiple formats for different platforms. Learn how to repurpose video content to maximize reach and ROI.",
  definition: "Content repurposing is the practice of adapting a single piece of content into multiple formats, lengths, and styles for distribution across different platforms and audiences. A 3-minute YouTube video becomes a 30-second TikTok clip, an Instagram carousel, a blog post, and an email snippet. Repurposing maximizes the ROI of every piece of content by extracting multiple assets from a single creative investment.",
  whyMatters: [
    { label: "It multiplies content ROI", text: "Creating one piece of content and using it once is the most expensive way to produce content. Repurposing that same piece into 5–10 formats across 3–4 platforms multiplies its value by 5–10x without proportional cost increases. A $200 video that becomes 8 pieces of content effectively costs $25 per piece." },
    { label: "Different platforms need different formats", text: "Your audience is spread across TikTok, Instagram, YouTube, Facebook, email, and your website — and each platform has different format requirements and audience expectations. Repurposing ensures you're present everywhere your audience is, in the format each platform rewards, without producing entirely new content for each channel." },
    { label: "It reinforces messaging through repetition", text: "Marketing's 'Rule of 7' says prospects need 7+ touchpoints before converting. Repurposed content creates these touchpoints across platforms — a prospect might see your TikTok ad, then your Instagram Reel, then your YouTube Short, each delivering the same core message in a platform-native format. The repetition builds familiarity and trust without feeling repetitive because each format feels fresh." },
  ],
  howItWorks: [
    { heading: "The Repurposing Pyramid", text: "Start with your highest-effort content (a long-form video, a detailed blog post, or a comprehensive guide) and work downward: Long-form video → short-form clips (TikTok, Reels, Shorts) → static quote cards → blog post → email newsletter → social media captions → podcast talking points. Each level requires less effort than the original but reaches a different audience segment. The pyramid ensures maximum distribution from minimum original production." },
    { heading: "Video Repurposing Specifically", text: "Video is the most repurposable format. A single 60-second video can be repurposed into: the full 60-second version for Instagram Reels, a 30-second cut for TikTok (focusing on the hook and key message), a 15-second cut for Stories and pre-roll, a thumbnail image for static ads, a GIF for email marketing, a transcript for blog content, and audio for podcast clips. Each derivative requires minimal additional production but reaches a new audience or platform." },
  ],
  example: "A DTC brand creates one 45-second AI-generated UGC video. They repurpose it into: (1) full 45-second version for Instagram Reels and Facebook Reels, (2) 25-second cut focusing on the hook and product reveal for TikTok, (3) 15-second cut for Instagram Stories ads, (4) the hook (first 5 seconds) as a GIF for email campaigns, (5) a screenshot with the key quote as a static image ad, and (6) the script adapted as ad copy for a carousel ad. One video, 6 assets, 4 platforms. Total additional production time: 30 minutes of editing. The repurposed assets generate 40% of the brand's total ad impressions for the month.",
  product: {
    intro: "ReUGC creates content that's designed for repurposing from the start:",
    points: [
      "Modular video structure — Videos generated by ReUGC have clear hook, body, and CTA sections that can be easily separated for platform-specific cuts. One generation, multiple usable assets.",
      "Multiple lengths from one script — Generate a 45-second full version and a 20-second cut from the same script. Different platforms prefer different lengths — cover them all without separate productions.",
      "Volume enables platform-specific content — With 10–60 videos per month ($49–$199/mo), you can create platform-optimized versions rather than forcing one video to work everywhere. True repurposing, not lazy cross-posting.",
    ],
  },
  related: [
    { term: "Content Velocity", slug: "content-velocity" },
    { term: "Short-Form Video", slug: "short-form-video" },
    { term: "Evergreen Content", slug: "evergreen-content" },
    { term: "Organic Social", slug: "organic-social" },
    { term: "Video Localization", slug: "video-localization" },
    { term: "Brand Kit", slug: "brand-kit" },
  ],
  relatedNote: "Content repurposing is a key driver of content velocity — producing more assets from fewer original pieces. It's most effective with short-form video (the most repurposable format) and evergreen content (which stays relevant across repurposed formats). Video localization is a form of repurposing for different markets. A brand kit ensures repurposed content stays on-brand across formats.",
};
export default data;
