import type { GlossaryPageData } from "./_shared";

const data: GlossaryPageData = {
  term: "Short-Form Video",
  h1: "What Is Short-Form Video? Under 60 Seconds Explained",
  meta: "Short-form video is video content under 60 seconds, optimized for platforms like TikTok, Reels, and Shorts. Learn why it dominates social media and how to create it effectively.",
  definition: "Short-form video is video content typically lasting 15–60 seconds, designed for vertical viewing on mobile devices. It's the dominant content format on TikTok, Instagram Reels, YouTube Shorts, and Facebook Reels — and it's become the most effective format for social media advertising, outperforming longer content in engagement, completion rates, and conversion metrics.",
  whyMatters: [
    { label: "It's where attention lives", text: "The average person spends 95 minutes per day watching short-form video. TikTok alone has over 1.5 billion monthly active users, and Instagram Reels accounts for 30%+ of time spent on Instagram. Short-form video isn't a trend — it's the primary way people consume content on mobile devices, and it's where your customers are spending their time." },
    { label: "It outperforms every other ad format", text: "Short-form video ads deliver 2–3x higher engagement rates than static images and 1.5–2x higher CTR than long-form video ads. The format's native feel (it looks like content, not advertising) bypasses ad blindness and earns genuine attention. For performance marketers, short-form video is the highest-ROI creative format available." },
    { label: "It's the most shareable format", text: "Short-form videos are shared 2x more than any other content type on social media. Shares are the most valuable engagement signal because they extend your reach for free and carry implicit endorsement from the sharer. A short-form video that gets shared effectively becomes UGC — real people distributing your message to their networks." },
  ],
  howItWorks: [
    { heading: "Anatomy of Effective Short-Form Video", text: "The best short-form videos follow a tight structure: hook (0–3 seconds) that stops the scroll, body (3–20 seconds) that delivers value or builds desire, and CTA (final 3–5 seconds) that drives action. Every second must earn the next second — there's no room for slow intros, lengthy logos, or filler content. The pacing should feel like a conversation, not a presentation. Captions are essential (85% of social video is watched without sound), and the visual should be engaging even on mute." },
    { heading: "Platform-Specific Considerations", text: "While the core format is similar across platforms, each has nuances. TikTok rewards raw, authentic content and trending audio. Instagram Reels favors slightly more polished content with strong visual aesthetics. YouTube Shorts benefits from educational or how-to content. Facebook Reels performs best with relatable, emotional content. The ideal length also varies: TikTok sweet spot is 21–34 seconds, Reels is 15–30 seconds, and Shorts is 30–58 seconds." },
  ],
  example: "A fitness supplement brand tests two ad formats on Meta: a 90-second product explainer video and a 28-second UGC-style testimonial. The short-form video delivers 47% higher completion rate, 2.1x higher CTR, and 38% lower CPA. They then produce 15 short-form variations using AI-generated presenters — testing different hooks, testimonial angles, and CTAs. The top 3 performers run for 2 weeks before being refreshed with new variations, maintaining consistent sub-$20 CPAs throughout the month.",
  product: {
    intro: "ReUGC is purpose-built for short-form video production:",
    points: [
      "Optimized for 15–60 seconds — Every video generated by ReUGC is designed for the short-form format. Pacing, delivery, and structure are tuned for the attention dynamics of TikTok, Reels, and Shorts.",
      "Vertical-first (9:16) — All output is in the vertical format that short-form platforms require. No cropping, no letterboxing, no reformatting needed. Upload directly from ReUGC to your ad platform.",
      "Volume for the short-form content machine — Short-form video's effectiveness depends on variety and freshness. Generate 10–60 videos per month ($49–$199/mo) to keep your content pipeline full across every platform.",
    ],
  },
  related: [
    { term: "Vertical Video", slug: "vertical-video" },
    { term: "Long-Form Video", slug: "long-form-video" },
    { term: "Hook", slug: "hook" },
    { term: "UGC Ads", slug: "ugc-ads" },
    { term: "Scroll-Stopping Content", slug: "scroll-stopping" },
    { term: "Content Velocity", slug: "content-velocity" },
  ],
  relatedNote: "Short-form video is defined by its vertical format and brief duration. Its effectiveness depends on strong hooks, scroll-stopping techniques, and the UGC aesthetic that social platforms reward. Content velocity — the ability to produce short-form content at scale — is what separates brands that thrive on these platforms from those that struggle.",
};
export default data;
