import type { CreatePageData } from "./_shared";
const data: CreatePageData = {
  title: "Create AI Multilingual Videos — One Script, 29 Languages",
  readTime: "8 min",
  meta: "Create AI multilingual videos that reach global audiences in their native language. Includes script framework, hook templates, and best practices for localized content.",
  intro: "72% of consumers prefer to buy products in their native language, and localized ads see 30% higher conversion rates than English-only campaigns. The global e-commerce market is $6.3 trillion — but most brands only advertise in one language. The reason is simple: multilingual video production is prohibitively expensive. Translating scripts, hiring native-speaking presenters, and producing separate videos for each market costs $2,000–$5,000 per language. For 10 languages, that's $50,000 per campaign. AI-generated multilingual videos eliminate this barrier entirely. Write one script, select your languages, and produce native-language videos with natural pronunciation and cultural nuance — at a fraction of the cost of traditional localization.",
  what: {
    definition: "A multilingual video delivers the same message in multiple languages using AI-generated presenters who speak each language naturally. It's the fastest way to localize video content for global markets without hiring native speakers or dubbing studios.",
    reasons: [
      { label: "Market expansion", text: "Every language you add opens a new market. Spanish alone gives you access to 500 million speakers across 20+ countries. French covers 29 countries. Portuguese reaches Brazil's 215 million consumers. One script, multiple markets." },
      { label: "Native trust", text: "People trust content in their language. A Spanish speaker watching a Spanish-language ad feels the brand made an effort to reach them specifically. This perceived effort translates to higher trust and conversion rates." },
      { label: "Competitive advantage", text: "Most competitors only advertise in English. Launching multilingual campaigns gives you first-mover advantage in underserved markets where CPMs are lower and competition is thinner." },
    ],
  },
  framework: [
    { step: "The Hook", time: "0–3 seconds", what: "Open in the target language with a hook that resonates culturally. The first words should signal 'this content is for you.'", examples: ["\"[Hook in target language] — opening in the viewer's native language immediately signals relevance and earns attention.\"", "\"If you've been looking for [product type], this is for you. [Delivered in native language]\""], why: "Hearing your native language in an ad creates an instant connection. It signals that the brand cares about your market specifically, not just translating an afterthought.", mistake: "Using a direct word-for-word translation of an English hook. Idioms, humor, and cultural references don't translate literally. Adapt the hook for each culture." },
    { step: "The Setup", time: "3–8 seconds", what: "Present the problem in culturally relevant terms. The pain point should resonate with the specific market.", examples: ["\"In [market], finding quality [product type] that ships reliably and doesn't cost a fortune is nearly impossible. Most international brands charge double for shipping and take 3 weeks to deliver.\""], why: "Market-specific pain points show you understand the local experience. Mentioning shipping and pricing concerns specific to that region demonstrates genuine localization, not just translation.", mistake: "Using US-centric examples in international markets. '$300' means different things in different economies. Adapt pricing references and cultural context." },
    { step: "The Payoff", time: "8–20 seconds", what: "Present the solution with market-specific benefits — local shipping, local currency pricing, or region-specific results.", examples: ["\"We ship to [country] in 5–7 days with free shipping over [local currency amount]. Over 3,000 customers in [country] already use this daily. Same product, same quality, delivered to your door.\""], why: "Local shipping times, local currency, and local customer counts make the product feel accessible and proven in their market. It's not a foreign product — it's available locally.", mistake: "Forgetting to localize the details. Shipping times, currency, and customer counts should be specific to the target market." },
    { step: "The CTA", time: "last 3–5 seconds", what: "Direct to a localized landing page or store with a CTA in the target language.", examples: ["\"[CTA in target language] — Link in bio for [country]-specific pricing and shipping.\"", "\"Try it yourself. We ship to [country]. Link below.\""], why: "A localized CTA with country-specific shipping confirmation removes the last barrier for international buyers: 'do they even ship here?'" },
  ],
  exampleScript: `[HOOK — 0-3s]\n"[Delivered in target language]\n'If you've been searching for a skincare product that actually works — and ships to [country] — keep watching.'"\n[Direct to camera, native language delivery]\n\n[SETUP — 3-8s]\n"[In target language]\n'Most international brands either don't ship here, charge ridiculous shipping fees, or take a month to arrive. I get it — it's frustrating. You deserve the same access to quality products as everyone else.'"\n[Empathetic, culturally aware tone]\n\n[PAYOFF — 8-18s]\n"[In target language]\n'This brand ships to [country] in 5-7 days. Free shipping over [local currency amount]. And over 2,000 customers here already use it. The results are the same — clearer skin in 2-3 weeks. Same formula, same quality, delivered to your door.'"\n[Show product, local shipping details]\n\n[CTA — 18-22s]\n"[In target language]\n'Try it. Link in bio for [country] pricing. You won't regret it.'"\n[Confident close, point to link]`,
  hooks: [
    { line: "[In native language]: 'Finally, a [product] that ships to [country] without the insane markup.'", trigger: "Addresses the #1 frustration of international shoppers — availability and pricing. Speaking in their language signals the brand serves their market.", products: "Any product expanding internationally — beauty, supplements, tech, fashion" },
    { line: "[In native language]: 'Over 3,000 people in [country] already use this. Here's why.'", trigger: "Local social proof is more persuasive than global numbers. '3,000 in your country' feels more relevant than '100,000 worldwide.'", products: "Products with existing international customer bases" },
    { line: "[In native language]: 'This product went viral in the US. Now it's available in [country].'", trigger: "US viral status creates aspirational appeal in international markets. The viewer gets access to something previously unavailable.", products: "Products with US market traction expanding globally" },
  ],
  bestPractices: [
    { label: "Ideal length", text: "15–30 seconds for social ads, 30–60 seconds for landing pages. Keep multilingual content concise — the language itself is the differentiator, not the length." },
    { label: "Cultural adaptation", text: "Don't just translate — localize. Adapt idioms, humor, pricing references, and cultural context for each market. A joke that works in English might fall flat in Japanese." },
    { label: "Local proof points", text: "Include market-specific data — local customer counts, local shipping times, local currency pricing. Global stats feel distant; local stats feel relevant." },
    { label: "Market prioritization", text: "Start with your highest-potential markets. Spanish, French, Portuguese, German, and Japanese cover the largest addressable audiences outside English." },
    { label: "Landing page alignment", text: "Every multilingual video should link to a localized landing page. Sending a Spanish-speaking viewer to an English website kills the conversion you just earned." },
    { label: "Captions", text: "Use captions in the target language with the same formatting as your English content. Consistent visual branding across languages maintains brand recognition." },
  ],
  whenToUse: {
    stage: "All funnel stages in new markets. Multilingual videos serve as awareness content in new markets and conversion content in established international markets.",
    audience: "Non-English-speaking consumers in your target markets. Prioritize markets with high demand for your product category and low competition from localized competitors.",
    platforms: "TikTok (global reach), Instagram, Facebook, YouTube. Each platform has different language demographics — research where your target language audience is most active.",
    pairWith: "Follow multilingual awareness ads with localized testimonial and review content. The awareness ad introduces the product in their language; the testimonial provides local social proof.",
  },
  ctaLine: "Create multilingual videos that reach global audiences in their language. One script, 29 languages, zero translation agencies.",
};
export default data;