import type { IndustryPageData } from "./_shared";

const data: IndustryPageData = {
  name: "B2B Software",
  h1: "AI UGC Videos for B2B Software: Make Enterprise Software Feel Human",
  updated: "March 2026",
  meta: "How B2B software companies use AI UGC video to humanize product marketing, scale demo content, and lower CAC. Includes 4 video formats, 5 hooks, and real cost breakdowns.",
  intro: "B2B software marketing has a content problem that nobody talks about: your product is complex, your sales cycle is long, and your audience is tired of watching the same polished explainer video with stock music and animated dashboards. Meanwhile, B2C brands are running 30+ UGC-style ads per month on LinkedIn and Meta — and they're stealing attention from your $50K/year contracts. The B2B brands winning right now are the ones that make enterprise software feel approachable. A real person (or a convincing AI one) talking about a real problem they solved with your tool. This guide covers how B2B software companies are using AI UGC to produce that content at scale.",
  challenges: [
    { title: "Your product is too complex for a 30-second ad", text: "B2B software solves nuanced problems. Explaining what your platform does in 30 seconds without jargon is genuinely hard. Most UGC creators can't speak credibly about enterprise workflows, data pipelines, or compliance automation — so the content either oversimplifies or loses the audience." },
    { title: "Customer testimonials are locked behind legal and NDA walls", text: "Your best marketing asset is a customer saying 'this tool saved us 40 hours a week.' But getting that testimonial approved by their legal team takes 3–6 months — if it happens at all. You need testimonial-style content without the testimonial approval process." },
    { title: "LinkedIn and Meta need volume, but B2B content is expensive to produce", text: "A single B2B case study video costs $3,000–$8,000 to produce. You need 15–20 creatives per month to test effectively on LinkedIn and Meta. At those rates, your content budget would exceed your ad spend." },
    { title: "Your audience is skeptical of polished marketing", text: "B2B buyers — especially technical ones — distrust slick production. They want to hear from peers, not from your marketing team. UGC-style content outperforms polished brand videos by 2–3x on LinkedIn, but producing authentic-feeling content at scale is the challenge." },
  ],
  formats: [
    { name: "The Peer Testimonial", why: "B2B buyers trust peers more than brands. This format features an AI presenter speaking as a user persona — a VP of Marketing, a RevOps lead, a CTO — describing a specific problem they solved with the software.", length: "30–45 seconds", platform: "LinkedIn, Facebook Feed", outline: ["Hook: \"We were spending 15 hours a week on reporting before we found this tool\"", "Describe the specific pain point in role-appropriate language", "\"Now it takes 20 minutes. I'm not exaggerating.\"", "CTA: \"If your team is still doing this manually, check the link\""] },
    { name: "The Feature Spotlight", why: "B2B buyers want to know what the product actually does. This format focuses on one specific feature and its impact — not a product tour, but a 'here's the one thing that changed everything' narrative.", length: "20–30 seconds", platform: "LinkedIn, YouTube Shorts", outline: ["Hook: \"There's one feature in [product] that our whole team talks about\"", "Name the feature and what it does in plain language", "Quantify the impact: \"It cut our onboarding time from 3 weeks to 4 days\"", "CTA: \"See it in action — link in the comments\""] },
    { name: "The Problem Agitation", why: "B2B audiences respond to content that articulates their pain better than they can. This format doesn't even mention the product until the last 5 seconds — it spends 25 seconds making the viewer feel seen.", length: "25–35 seconds", platform: "TikTok, LinkedIn", outline: ["Hook: \"If you're a [role] and you're still using spreadsheets for [task], I feel your pain\"", "List 2–3 specific frustrations that come with the manual process", "\"There's a better way and it takes 10 minutes to set up\"", "CTA: \"Link in bio — your spreadsheet era is over\""] },
    { name: "The ROI Calculator", why: "B2B buyers need to justify purchases internally. This format does the math for them — showing the time or money saved in concrete terms that they can bring to their CFO.", length: "25–35 seconds", platform: "LinkedIn, Facebook Feed", outline: ["Hook: \"Let me do the math on what manual [task] is costing your team\"", "\"If you have 5 people spending 3 hours/week on this, that's 780 hours/year\"", "\"At $75/hour fully loaded, that's $58,500 in labor on something a tool can do\"", "CTA: \"[Product] costs less than one month of that. Link below.\""] },
  ],
  stats: [
    { num: "50x", label: "cheaper than B2B video production", context: "A single B2B testimonial video costs $3,000–$8,000 to produce with a real customer. AI UGC produces equivalent testimonial-style content at $4–$8 per video — without the 3-month legal approval process." },
    { num: "2–3x", label: "higher engagement than polished brand videos", context: "UGC-style content consistently outperforms polished brand videos on LinkedIn and Meta for B2B audiences. The authentic, peer-to-peer feel drives more clicks, comments, and shares." },
    { num: "40%", label: "lower CAC with high-volume creative testing", context: "B2B companies that increase creative testing from 3–5 to 15–20 per month typically see CAC drop by 40% within 90 days — because different personas respond to different pain points, and you need volume to find the matches." },
  ],
  hooks: [
    { line: "We were paying 3 people full-time to do what this tool does in 10 minutes.", why: "Quantifies the problem in headcount — the most relatable metric for B2B decision-makers. Creates immediate curiosity about what the tool is.", tag: "ROI" },
    { line: "I showed this to our CTO and he cancelled our internal build the same day.", why: "Implies the product is so good it replaced a custom solution. The CTO reference adds technical credibility.", tag: "Social Proof" },
    { line: "If your team is still using spreadsheets for this, I'm sorry.", why: "Empathy + mild provocation. The viewer who IS using spreadsheets feels called out — and wants to know the alternative.", tag: "Problem Agitation" },
    { line: "The tool our competitors don't want you to know about.", why: "Competitive framing creates urgency. B2B buyers are always watching what competitors are doing.", tag: "Competitive" },
    { line: "POV: you automate the task your team has been complaining about for 2 years", why: "Speaks to the internal frustration that B2B buyers live with daily. The '2 years' specificity makes it feel real.", tag: "Relatability" },
  ],
  stories: [
    { brand: "A project management SaaS doing $2M ARR", challenge: "Needed LinkedIn video ads but couldn't get customer testimonials approved — their enterprise clients all had strict media policies. Their only option was polished brand videos that underperformed.", did: "Used ReUGC Pro plan ($99/month) to create 25 persona-based testimonial videos. Each featured an AI presenter speaking as a specific role (PM, VP Eng, COO) describing problems the product solves — without naming any real customer.", result: "LinkedIn ad CTR increased 2.4x compared to their polished brand videos. CAC dropped 35% in 60 days. Content spend went from $5,000/month (agency) to $99/month." },
    { brand: "A data analytics platform scaling paid acquisition", challenge: "Running the same 3 explainer videos for 6 months. Creative fatigue had pushed CPA up 70% on Meta, but producing new B2B video content took 4–6 weeks per batch.", did: "Switched to ReUGC Pro Plus ($199/month). Created 60 videos — 12 per persona (5 target personas), each with different hooks and pain points.", result: "CPA dropped back to baseline within 3 weeks. Found that the 'ROI Calculator' format outperformed all other formats by 3x — a discovery they couldn't have made testing 3 videos at a time." },
    { brand: "A compliance software startup entering the EU market", challenge: "US campaigns were profitable but EU compliance requirements differ significantly. Needed localized content that spoke to GDPR-specific pain points in German, French, and Dutch.", did: "Adapted their top 5 US scripts for EU compliance language and generated 15 localized videos across 3 languages on the Pro plan ($99/month).", result: "Launched EU campaigns within 8 days. German market hit target CAC in the first month. Total content cost for 3-market launch: $99." },
  ],
  faq: [
    { q: "Can AI UGC work for complex B2B products?", a: "Yes — the key is scripting. AI presenters deliver exactly what you write, so if your script explains the value proposition clearly and uses the right persona language, the output is convincing. Most B2B brands find that writing good scripts is easier than finding creators who understand their product." },
    { q: "Is UGC-style content appropriate for enterprise software?", a: "Absolutely. LinkedIn data shows that UGC-style video outperforms polished brand content by 2–3x for B2B audiences. Enterprise buyers are still humans scrolling a feed — they respond to authentic, peer-to-peer communication." },
    { q: "How do you handle the testimonial problem without real customers?", a: "AI UGC lets you create persona-based testimonials — an AI presenter speaking as a 'VP of Marketing at a mid-market SaaS company' describing a problem your product solves. It's testimonial-style content without naming any real customer or requiring legal approval." },
    { q: "What plan works best for B2B software companies?", a: "Pro ($99/month, 25 videos) is ideal for most B2B companies running LinkedIn and Meta campaigns. If you're targeting multiple personas across multiple markets, Pro Plus ($199/month, 60 videos) gives you the volume to test effectively." },
  ],
  ctaLine: "Make enterprise software feel human. Get started.",
};
export default data;
