import type { IndustryPageData } from "./_shared";

const data: IndustryPageData = {
  name: "Coaches & Consultants",
  h1: "AI UGC Videos for Coaches & Consultants: Scale Your Personal Brand Without Being on Camera 24/7",
  updated: "March 2026",
  meta: "How coaches and consultants use AI UGC video to generate leads, build authority, and scale ad creative without filming themselves. Includes 4 video formats, 5 hooks, and real stories.",
  intro: "Every coach and consultant hits the same wall: your business grows when you create content, but creating content takes time away from actually coaching and consulting. You're stuck in a cycle of filming talking-head videos, editing them yourself, and posting 3x a week just to stay visible. And when you try to scale with paid ads, you realize you need 15–20 different creatives to test — which means 15–20 more hours in front of a camera. This guide covers how coaches and consultants are using AI UGC to produce client-getting video content at scale, without spending their entire week filming.",
  challenges: [
    { title: "Your face is your brand — but you can't scale yourself", text: "Coaching businesses are built on personal connection. Your audience wants to see and hear from you. But there are only so many hours in a day, and every hour filming is an hour not coaching. You need a way to produce content volume without being the bottleneck." },
    { title: "Testimonial content is your best converter — and hardest to produce", text: "Nothing sells coaching like a client saying 'I 3x'd my revenue in 6 months.' But getting clients to record quality video testimonials is difficult. They're busy, they're camera-shy, and the footage quality is usually unusable for paid ads." },
    { title: "Ad creative fatigue kills your funnel", text: "Most coaches run 2–3 ads until they stop working, then scramble to create new ones. The cycle of film → edit → launch → fatigue → repeat is exhausting and unsustainable. You need a content engine that doesn't depend on your availability." },
    { title: "Different offers need different messaging", text: "A $97 digital course, a $2,000 group program, and a $10,000 1-on-1 package all need different ad creative, different hooks, and different social proof. But you're one person trying to create content for all three." },
  ],
  formats: [
    { name: "The Client Transformation Story", why: "Coaching is sold on outcomes. This format features an AI presenter sharing a transformation story based on real client results — the before state, the coaching experience, and the measurable after.", length: "30–40 seconds", platform: "Facebook Feed, Instagram Reels", outline: ["Hook: \"I was stuck at $8K/month for 2 years. Then I hired a coach.\"", "Describe the before: specific, relatable, and honest", "\"In 90 days, we rebuilt my offer, my funnel, and my pricing\"", "Share the result: \"Last month I did $34K. Same audience, completely different approach.\"", "CTA: \"Ready for your transformation? Link in bio.\""] },
    { name: "The Framework Teaser", why: "Coaches sell frameworks and methodologies. This format reveals one piece of a framework — enough to demonstrate expertise and create curiosity about the full system. It positions you as the expert without giving everything away.", length: "25–35 seconds", platform: "TikTok, YouTube Shorts", outline: ["Hook: \"The 3-step framework that took me from $5K to $50K months\"", "Reveal step 1 in detail — make it genuinely valuable", "Tease steps 2 and 3: \"Steps 2 and 3 are where the real leverage is\"", "CTA: \"Full framework in my program. Link below.\""] },
    { name: "The Objection Buster", why: "Coaching has massive objection barriers: 'I can't afford it,' 'I can figure it out myself,' 'coaching is a scam.' This format addresses the #1 objection directly and reframes it.", length: "20–30 seconds", platform: "TikTok, Instagram Reels", outline: ["Hook: \"'I can't afford a coach' — I used to say the same thing\"", "\"Then I calculated how much money I was losing by figuring things out alone\"", "\"6 months of trial and error cost me $40K in missed revenue\"", "CTA: \"The real question is: can you afford NOT to? Link in bio.\""] },
    { name: "The Authority Positioning Clip", why: "Coaches need to establish credibility before they can sell. This format shares a contrarian insight or industry truth that positions you as someone who thinks differently — attracting the right clients and repelling the wrong ones.", length: "20–30 seconds", platform: "TikTok, LinkedIn", outline: ["Hook: \"Unpopular opinion: most business coaches are teaching 2019 strategies\"", "Share the contrarian insight with specific reasoning", "\"Here's what's actually working right now for my clients\"", "CTA: \"Want the full playbook? Link in bio.\""] },
  ],
  stats: [
    { num: "50x", label: "cheaper than hiring UGC creators", context: "Coaching-focused UGC creators charge $300–$600 per testimonial video. With ReUGC, you produce the same testimonial-style content at $4–$8 per video — and you control every word of the script." },
    { num: "10–15 hrs", label: "saved per month on content creation", context: "Most coaches spend 10–15 hours per month filming, editing, and producing ad content. AI UGC reduces that to 2–3 hours of script writing — the rest is automated." },
    { num: "3–5x", label: "more ad variations tested", context: "Coaches using AI UGC test 15–25 ad variations per month instead of the typical 3–5. More variations means faster identification of the hooks and stories that drive applications and enrollments." },
  ],
  hooks: [
    { line: "I invested $15K in a coach and made it back in 6 weeks.", why: "Specific ROI with a tight timeline. Creates curiosity about what the coach taught that produced such fast results.", tag: "ROI" },
    { line: "My coach told me to raise my prices and I almost fired her. Best advice I ever got.", why: "Narrative tension — the viewer wants to know why raising prices worked. The 'almost fired her' adds drama.", tag: "Transformation" },
    { line: "I was working 70-hour weeks making $10K/month. Now I work 25 hours making $40K.", why: "The lifestyle transformation is more compelling than the revenue number alone. Speaks to the burnout that drives people to seek coaching.", tag: "Lifestyle" },
    { line: "POV: you finally hire a coach and realize you've been doing everything the hard way", why: "Relatable for anyone who's been grinding alone. The 'hard way' implies there's an easier path — which is what coaching offers.", tag: "Relatability" },
    { line: "Stop watching free content and wondering why nothing changes.", why: "Direct challenge to the viewer's current behavior. Provocative enough to stop the scroll and make them reconsider.", tag: "Provocation" },
  ],
  stories: [
    { brand: "A business coach doing $60K/month in program sales", challenge: "Spending 12 hours/week filming content for ads and organic social. Couldn't scale ad spend because she was the bottleneck for all creative production. Hiring UGC creators at $500/video didn't match her brand voice.", did: "Switched to ReUGC Pro plan ($99/month). Created 25 client transformation testimonials using AI presenters, plus 10 framework teaser videos — all scripted in her brand voice without her being on camera.", result: "Freed up 10 hours/week for actual coaching. Ad creative volume went from 4 to 25 per month. Cost per application dropped 44% as she could finally test at scale." },
    { brand: "A career coach launching a group program", challenge: "Needed 30+ creatives for a 10-day launch window. Previous launches used 5–6 videos and generated $80K. Knew more creative volume would improve results but couldn't film 30 videos in a week.", did: "Used ReUGC Pro Plus ($199/month) to generate 45 launch videos — transformation stories, objection busters, and framework teasers across multiple AI presenters matching her client demographics (women 28–45).", result: "Launch generated $210K — 2.6x her previous best. The high creative volume let her find 8 winning ads in the first 3 days, which she scaled aggressively for the remaining 7 days." },
    { brand: "A consulting firm scaling from referrals to paid acquisition", challenge: "Had zero ad creative. The partners were too busy with client work to film, and their $500/hour billing rate made filming content an expensive use of time.", did: "Built a library of 25 persona-based testimonial scripts (based on real client outcomes) and generated them with professional-looking AI presenters on the Pro plan ($99/month).", result: "Launched their first paid acquisition campaigns within a week. Generated 12 qualified leads in the first month at $180/lead — well below their $500 target. Now running always-on campaigns without any partner filming time." },
  ],
  faq: [
    { q: "Can AI UGC work if my personal brand is the business?", a: "Yes — AI UGC handles the testimonial and social proof layer of your content. You still show up for organic content and thought leadership, but your paid ads feature AI presenters sharing client transformation stories. This lets you scale ad creative without being on camera for every single video." },
    { q: "How do I maintain my brand voice with AI presenters?", a: "The voice comes from the script, not the presenter. Write scripts in your tone, with your frameworks and language, and the AI delivers them consistently. Most coaches find that scripting is actually easier than improvising on camera." },
    { q: "What about using real client testimonials?", a: "Use both. Real client testimonials are gold for organic content and your website. AI UGC handles the volume you need for paid advertising — 15–25 variations per month that you can't get from real clients." },
    { q: "Which plan is right for a coaching business?", a: "Starter ($49/month, 10 videos) for coaches just starting with paid ads. Pro ($99/month, 25 videos) for coaches running consistent campaigns or preparing for launches. Pro Plus ($199/month, 60 videos) for coaches with multiple offers or running large launch campaigns." },
  ],
  ctaLine: "Scale your coaching content without scaling your filming schedule. Get started.",
};
export default data;
